### ISSUE TITLE
Repenser le frontend avec React Native Web

### ISSUE THREAD

**Issue by zoontek** [parisjs/talks#100]
## Repenser le frontend avec React Native Web

*Talk format :* Long

*Description :*

> Fort de mon expérience au sein de Swan.io ou nous utilisons massivement React Native Web, j'ai depuis longtemps l'idée d'un talk sur la façon dont je conçois le frontend aujourd'hui. Au menu:
> - Des abstractions qui font sens pour le web d'aujourd'hui (`View`, `Text`, `FlatList`, etc: expliquer pourquoi c'est bien)
> - L'intérêt d'un couplage CSS-in-JS / Animations / Gestures fort
> - Des interdictions qu'on s'impose pour augmenter la maintenabilité (pas de pseudo classes, pas de margins, modality / focus-visible only, pas de :hover sans le media-query hover, etc)
> - Les meta components: `<Space />`, `<Divider />`, `<SpaceAround />`, `<Fill />`, `<Stack />`, etc.
> - L'aide du type system pour respecter les couleurs, espacements, etc
> - Les notions de layering avec / sans focus trap
> - Un live-coding d'une `BottomSheet` custom (déjà fait pour un autre talk) pour montrer la puissance de tout ça une fois packé

À noter que ce talk présentera RNW, mais qu'il sera explicitement dit que la pensée n'est pas liée à a techno. Les primitives présentes out-of-the-box étant facilement réimplémentables avec autre chose, un petit example sera donné (avec `emotion`)

*Slides :* 
*Projet :* https://github.com/necolas/react-native-web
*Twitter :* @zoontek

**Comment by mauricesvay** [comment]
Hello @zoontek !

Merci d'avoir proposé un sujet. On envisage de relancer les meetups dans une formule 100% en ligne, avec des talks un plus courts (10-15 minutes).

- Est-ce que ton sujet est toujours d'actualité?
- Est-ce qu'il pourrait être adapté à un format plus court?

**Comment by zoontek** [comment]
Hello @mauricesvay ! Oui il est toujours d'actualité, mais ça va être chaud de faire tenir ça sur 10-15 min tellement le sujet est vaste.

**Comment by Freddy03h** [comment]
Hello @zoontek ! Est ce que tu es dispo pour le prochain parisJS du mercredi 31 mars ? Merci !

**Comment by zoontek** [comment]
Hello @Freddy03h! Oui je serais dispo. Néanmoins vu le temps (10-15 min) je vais restreindre le sujet afin de tenir.

Plutôt que de parler de repenser le web au global, je vais m'en tenir aux primitives et React Native Web ne sera plus utilisé qu'en point de comparaison (c'est normalement la première partie de mon talk).

Le talk s'intitulera donc "Le web mérite de meilleures primitives". Est-ce que cela vous convient?
