### ISSUE TITLE
Intéraction entre une application web et un lecteur NFC USB fait maison : l'API WebUSB à la rescousse !

### ISSUE THREAD

**Issue by gdarchen** [parisjs/talks#101]
## Intéraction entre une application web et un lecteur NFC USB fait maison : l'API WebUSB à la rescousse !

*Talk format :* Long

*Description :*

> Lorsqu'on développe un outil qui interagit avec un périphérique, nous sommes encore forcés de développer des clients lourds ou d'utiliser des conteneurs comme Electron.
Pourquoi ne pas directement utiliser le navigateur?
Eh oui, vos browsers, et notamment Chrome, ont de plus en plus d'APIs vous permettant d'accéder à des parties natives de vos équipements. 
Viens découvrir la WebUSB API à travers un exemple simple : la réalisation d'un lecteur de carte NFC en 100% web.

*Slides :* https://slides.com/gautierdarchen/webusb-arduino-nfc
*Projet :* https://github.com/gdarchen/webusb-arduino-nfc
*Twitter :* https://twitter.com/gdarchen

**Comment by mauricesvay** [comment]
Hello @gdarchen !

Merci d'avoir proposé un sujet. On envisage de relancer les meetups dans une formule 100% en ligne, avec des talks un plus courts (10-15 minutes).

- Est-ce que ton sujet est toujours d'actualité?
- Est-ce qu'il pourrait être adapté à un format plus court?
