### ISSUE TITLE
Web perf : analyser et optimiser un front

### ISSUE THREAD

**Issue by Djoow** [parisjs/talks#102]
## Du make it work au make it fast : des quickwins pour booster votre application !

*Talk format :* Long

*Description :*

> _“Out of the box, webpack fait le café ! React c’est génial ; Uber, Airbnb, …, tout le monde l’utilise, avec ça le front de ton appli va être dingue !”_. Ce sont plus ou moins les phrases que j’ai pu entendre auprès des équipes des quelques projets sur lesquels j’ai eu l’occasion de travailler, et c’est vrai, ça marche. Ça marche même très bien. Mais au fait, qu’est ce que ça signifie _“ça marche”_ ? 
>
> Pourquoi mon application affiche-t-elle systématiquement un loader à son démarrage ? Pourquoi la version web de reddit me transfère-t-elle 16Mo de data avec pas moins de 236 requêtes rien que sur la page d'accueil ? Est ce qu'un _"web instantané"_ est possible ?
Je vous propose plusieurs optimisations simples à mettre en place pour enfin maîtriser le contenu affiché sur vos applications web et ainsi bluffer vos futurs utilisateurs. 

*Slides :* [https://slides.com/djow/makeitwork2makeitfast](https://slides.com/djow/makeitwork2makeitfast)
*Projet :* _(wip)_
*Twitter :* [https://twitter.com/djow__](https://twitter.com/djow__)

**Comment by mauricesvay** [comment]
Hello @Djoow !

Merci d'avoir proposé un sujet. On envisage de relancer les meetups dans une formule 100% en ligne, avec des talks un plus courts (10-15 minutes).

- Est-ce que ton sujet est toujours d'actualité?
- Est-ce qu'il pourrait être adapté à un format plus court?

**Comment by Djoow** [comment]
Hello @mauricesvay,

Merci de me contacter :) 
Oui bien sûr, je peux adapter mon talk pour un format plus court (je voulais de toute façon refacto un petit peu le contenu, là ça serait l'occasion).

Quel serait ton planning ?

**Comment by mauricesvay** [comment]
@Djoow pour le moment on essaie d'abord d'évaluer si un meetup 100% en ligne est faisable, on n'a pas pas encore défini le programme pour ce mois-ci. Si ton talk est retenu pour un des meetups, on te recontactera :)

**Comment by Djoow** [comment]
Ok super ! Pour le prochain meetup ça sera juste, mais ceux d'après ça devrait le faire. Merci !

**Comment by Freddy03h** [comment]
Hello @Djoow ! Est ce que tu serais dispo pour le meetup du 28 septembre ? merci !

**Comment by Djoow** [comment]
Hello @Freddy03h, oui je pense pouvoir donner ce talk pour l'édition du 28 septembre s'il reste encore une place :)

**Comment by Freddy03h** [comment]
Ok ! Alors oui je valide ton talk pour le mercredi 28 septembre !

**Comment by Djoow** [comment]
Top ! Au niveau du talk, je l'ai un peu retravaillé depuis. Le nom a changé : **Web perf : analyser et optimiser en React**

**Comment by Freddy03h** [comment]
Ok ! Tu peux modifier l'issue github stp ?
