### ISSUE TITLE
Introduction à l'architecture microservices

### ISSUE THREAD

**Issue by KajanSiva** [parisjs/talks#103]
## Introduction à l'architecture microservices

*Talk format :* Long

*Description :*

> De Netflix à Frichti, les architectures microservices ont le vent en poupe ces dernières années. Elles permettent aux entreprises de scaler leurs projets et leurs équipes.

> Dans ce talk, nous allons voir ensemble les principes de bases de ces architectures. Avec leurs avantages et inconvénients.

*Slides :* 
*Projet :* 
*Twitter :* 

J'avais donnée récemment ce talk au meetup Node.js, où j'avais eu de bons retours.

**Comment by mauricesvay** [comment]
Hello @KajanSiva !

Merci d'avoir proposé un sujet. On envisage de relancer les meetups dans une formule 100% en ligne, avec des talks un plus courts (10-15 minutes).

- Est-ce que ton sujet est toujours d'actualité?
- Est-ce qu'il pourrait être adapté à un format plus court?

**Comment by KajanSiva** [comment]
Hello @mauricesvay,

Oui, je pourrais l'adapter un peu pour l'écourter. Je dois le rafraîchir un peu dans tous les cas.
Tu connais déjà les dates de ces prochains meetups en ligne ?

**Comment by mauricesvay** [comment]
Le programme pour le 3 février est bouclé. Le prochain meetup sera vraisemblablement le dernier mercredi de février. Si ton sujet est sélectionné pour un futur meetup, on te recontactera.

**Comment by KajanSiva** [comment]
Ok, de mon côté je pourrais retravailler la présentation pour être prêt pour fin Février.

Tiens-moi au courant si mon talk est sélectionné pour un des prochains meetup.

**Comment by mauricesvay** [comment]
@KajanSiva je sais que c'est un peu à la dernière minute, mais est-ce que ça te dirait de présenter au meetup online du mercredi 3 mars? Si c'est OK pour toi, il me faudra juste un email pour que je t'envoie les infos pour les détails d'organisation.

**Comment by KajanSiva** [comment]
C'est bon pour moi @mauricesvay 👍 
Je t'ai envoyé mon mail sur le tien.
