### ISSUE TITLE
Serveur-client GraphQL via Apollo.

### ISSUE THREAD

**Issue by CaptainJojo** [parisjs/talks#11]
## Serveur-client GraphQL via Apollo.

*Talk format :* Long

*Description :*

> La révolution est en marche, GraphQL devient de plus en plus populaire. Mais c'est quoi ?
> GraphQL est un manifeste Facebook, qui met en place un language de query permettant de créer des APIs facilement, pouvant communiquer avec n'importe qu'elle source de données.

> Le talk permet de mettre en place un serveur GraphQL, avec un client React en utilisant la librairie Apollo. 

*Slides :* undefined
*Projet :* https://github.com/duck-invaders/graphql-apollo
*Twitter :* @captainjojo42

**Comment by PierrickP** [comment]
Salut, 
es-que tu serais dispo pour le prochain Paris.js, mercredi 26 septembre https://www.meetup.com/fr-FR/Paris-js/events/251642397/ ?
