### ISSUE TITLE
Un tour de l’onboarding à Doctolib

### ISSUE THREAD

**Issue by qmenoret** [parisjs/talks#115]
## Un tour de l’onboarding à Doctolib

*Talk format :* Long

*Description :*

> Mélanie Godard et Quentin Menoret, deux Doctolibers, vont vous parler de l’onboarding technique des développeurs fullstack qui rejoignent Doctolib.

> Vous en apprendrez plus sur:
> Le process d’onboarding
> La manière dont nous utilisons code tour
> L’extension code tours github, développée à Doctolib, qui permet de suivre un tour directement depuis votre navigateur.

*Slides :* 
*Projet :* 
*Twitter :* @bakablue & @qmenoret

**Comment by Freddy03h** [comment]
Hello ! Est ce que vous parlez aussi de l'onboarding des juniors dans le talk (notamment profil en reconversion, que l'on voit de plus en plus en meetup) ? Et est ce que vous parlez aussi des contraintes liées à la période actuelle aussi (remote) ? Et le maxi best-of : comment conjuguer ces deux problématiques ? Merci :)

**Comment by Freddy03h** [comment]
Up! @qmenoret ?

**Comment by qmenoret** [comment]
Hello, désolé pour la réponse tardive! On peut définitivement focus sur l'onboarding des juniors, surtout que l'on a pas mal de profils qui viennent de bootcamps / reconv donc on peut faire un bon retour d'xp je pense. On peut probablement aussi parler un peu d'onboarding remote.

**Comment by Freddy03h** [comment]
Cool, je pense ça serait sympa ! Est ce que tu penses pouvoir faire un talk qui tendrait en max 15 min pour le mercredi 31 mars ?
On a réduit le format pour que cela soit plus digeste en streaming, on s'est rendu compte que ça fonctionnait pas trop mal sur les deux derniers meetups.

**Comment by qmenoret** [comment]
Yes pas de problème, ce serait à quelle heure?

**Comment by Freddy03h** [comment]
19h

**Comment by qmenoret** [comment]
Ça marche, bah je m'organise avec @bakablue pour voir qui s'occupera du talk (ou si on reste deux) mais en tout cas on est partant!

**Comment by mauricesvay** [comment]
@qmenoret @bakablue Est-ce que vous pouvez m'envoyer un message à maurice.svay@gmail.com pour que je vous donne les infos pour l'organisation du meetup?
