### ISSUE TITLE
A la découverte du DevTool Protocol

### ISSUE THREAD

**Issue by vdeturckheim** [parisjs/talks#117]
## A la découverte du DevTool Protocol

*Talk format :* Long

*Description :*

> Tu as déjà ouvert les developper tools sur Chrome ou Chromium ?
> Tu as deja ouvert le debugger sur Node.js?
> Tu as déjà utilisé Puppeteer?

> Oui? Alors sans le savoir tu as utilisé de Chrome DevTools Protocol. Mais qu'est-ce que c'est que cette chose là? Ni plus ni moins que l'arme ultime pour rentrer dans les secrets de Chrome et V8.

> Dans ce talk, on va voir ce que c'est et comment l'utiliser. Allez viens, on est biens!

*Slides :* 
*Projet :* 
*Twitter :* @poledesfetes

**Comment by mauricesvay** [comment]
@vdeturckheim est-ce que tu penses que ça peut tenir dans 15 minutes pour un meetup online?

**Comment by vdeturckheim** [comment]
@mauricesvay jouable mais je serai pas pret pour le 3 :/

**Comment by mauricesvay** [comment]
@vdeturckheim pas de soucis !

**Comment by Freddy03h** [comment]
Hello @vdeturckheim ça va ? On tente de relancer les meetups, est ce que tu serais dispo le mercredi 24 novembre pour nous proposer ton talk ? Merci 😀

**Comment by Freddy03h** [comment]
Pas dispo pour le 24 nov., je mets de côté pour Janvier.

**Comment by vdeturckheim** [comment]
https://github.com/parisjs/talks/issues/147 est un superset de celui la - closing
