### ISSUE TITLE
Retour d'expérience : installation progressive de Redux son notre app React

### ISSUE THREAD

**Issue by Paul-Yves** [parisjs/talks#121]
## Mon titre

*Talk format :*  Short

*Description :*

Avec la prise de poids de notre app React, on a commencé à avoir pas mal de problème pour faire circuler des props et leur callback un peu partout. Le moment semblait idéal pour installer Redux. Retour d'expérience sur comment on s'y est pris pour faire ça progressivement sans sacrifier toute notre bande passante.

**Comment by mauricesvay** [comment]
@Paul-Yves hello, il reste un créneau pour demain. Est-ce que ça t'intéresse de présenter ?

**Comment by Paul-Yves** [comment]
Bonjour

Oui c'est jouable pour demain, il me faudra juste les détails de ce qu'il faut faire / mettre en place pour présenter.

**Comment by mauricesvay** [comment]
@Paul-Yves je t'envoie ça par mail ! Est-ce que tu peux m'envoyer ton adresse à maurice.svay at gmail.com?
