### ISSUE TITLE
Tout ce que vous devriez savoir sur Unicode, UTF-8 et autres

### ISSUE THREAD

**Issue by dubzzz** [parisjs/talks#123]
## Tout ce que vous devriez savoir sur Unicode, UTF-8 et autres 

*Talk format :* Long (30min)

*Description :*

> string est l'une des primitives principales en informatique, et ce quelque soit le langage. Pourtant, derrière son semblant de simplicité, se cache une énorme complexité inhérente aux spécifications Unicode. Ce talk a pour objectif de vous présenter ce que sont Unicode, UTF-8.. Afin que vous soyez prêt pour l'internationalisation de vos Apps.

*Projet :* https://github.com/dubzzz/fast-check/
*Twitter :* https://twitter.com/ndubien

**Comment by dubzzz** [comment]
Hello @Freddy03h,
**Ca va être difficile si c'est en présentiel.** Je n'habite plus sur Paris mais remonte quelques fois mais là ça va être un peu short de mon côté.
🤔

**Comment by Freddy03h** [comment]
Merci de ta réponse super rapide !!
En effet je comprend. À priori on garde le rythme de "dernier mercredi du mois" pour Paris.js, du coup les prochains seront 26 janvier, 23 février, … tu penses pouvoir à un de ces dates ?

**Comment by dubzzz** [comment]
26 janvier, ça pourrait être good! Je te confirme ça asap

**Comment by dubzzz** [comment]
@Freddy03h Je serai sur Paris le 26 Janvier donc dispo pour le talk ce jour-ci

**Comment by Freddy03h** [comment]
Cool ! Je te note alors pour le 26 janvier 😃

**Comment by dubzzz** [comment]
@Freddy03h, étant donné le risque COVID-19 en ce moment, je ne suis pas sûr de venir sur Paris fin Janvier. Je risque de décaler mes billets (initialement prévu) a plus tard.

**Comment by Freddy03h** [comment]
@dubzzz Ok pas de soucis, merci d'avoir prévenu !

**Comment by dubzzz** [comment]
Billets pris, je serai bien sur Paris le 27 avril 2022

**Comment by Freddy03h** [comment]
Hello @dubzzz ! Est ce que tu peux me reconfirmer ta présence pour le meetup du 27 avril stp ? :)
Et de rejoindre le Discord aussi stp pour échanger plus facilement : https://discord.gg/c45mRqQg (ping moi quand tu y sera pour que je t'ajoute au channel privé de l'event)
Merci :)

**Comment by dubzzz** [comment]
Yes, je confirme

**Comment by gabjauf** [comment]
@dubzzz It reminded me of your talk 😂 
<img src="https://imgs.xkcd.com/comics/vomiting_emoji.png"/>

**Comment by mauricesvay** [comment]
@dubzzz est-ce que tes slides sont dispo quelque part ? J'aimerais les intégrer dans la vidéo du talk

**Comment by dubzzz** [comment]
Les voici : https://dubzzz.github.io/fast-check.github.com/talks/meetup-parisjs-27042022/index.html
