### ISSUE TITLE
Faire de la perf sans être déçu

### ISSUE THREAD

**Issue by MathildeDuboille** [parisjs/talks#124]
## Faire de la perf sans être déçu

    *Talk format :* Long
  
    *Description :*
  
    > Ce talk est un retour d'experience sur un projet d'amélioration de performance pour un géant de e-commerce du luxe français.

> **Objectif :** Faire passer le score Lighthouse en 3G de 2/100 à 70/100. Ambitieux 🧐 ? Et oui... Mais avec une équipe de choc de 3 développeurs à temps plein sur le projet 🧑🏽‍💻👩🏼‍💻!

> Ce talk parlera du gros travail de performance qui a été fait sur un site SSR en NextJS, notamment avec :

> - 🌳 Une réduction drastique de la taille du bundle d'un facteur 3 grâce à du tree shaking et une chasse aux dépendances dupliquées dans un mono-repo.
> - 🤖 Une réduction de 4s sur le Time To Interactive grâce au lazy loading de nos pages mais aussi de nos composants React, tout ca sans impacter le SEO .
> - 💤 Une reduction de moitié du Total Blocking Time grâce à la mise en place d'une solution de Lazy Hydrating.

> Malgré tous ces efforts et l'enthousiasme de l’équipe, le projet a été marqué par de nombreux moments de deception. 

> Spoiler alert : Nous n'avons pas réussi à atteindre la barre des 70/100 ni même la barre des 20/100 en 3G. 

> Spoiler Alert 2 : En 4G, le score lighthouse est passé de 40 à plus de 95 /100 🎉. Les clients ont remarqué l'énorme amélioration de la performance du site et étaient donc très satisfaits.

> Si vous aussi vous avez peur d’être déçu sur vos améliorations de performance, ce talk vous donnera de précieux conseils pour savourer au maximum tous vos efforts.
  
    *Slides :* 
    *Projet :* 
    *Twitter :*

**Comment by Freddy03h** [comment]
Hello @MathildeDuboille ! On tente de relancer les meetups, est ce que tu serais dispo le mercredi 24 novembre pour nous proposer ton talk ? Merci 😀

**Comment by MathildeDuboille** [comment]
Hello, 

Désolée pour le temps de réponse j’ai été assez prise dernièrement. Malheureusement je ne serai pas dispo le 24 novembre, avec mon co-speaker on prépare notre passage à la We Love Speed qui a lieu le 16 décembre, je ne pense pas que l’on participera à d’autres événements d’ici là

Merci pour la sollicitation :)

Bonne journée,
Mathilde

**Comment by Freddy03h** [comment]
Pas de soucis, merci de ta réponse !

On garde le rythme de "dernier mercredi du mois" pour Paris.js, du coup les prochains seront 26 janvier, 23 février, … ton collègue et toi pensez pouvoir à une de ces dates ?

**Comment by MathildeDuboille** [comment]
Oui pourquoi pas en Janvier ! :) on peut se recontacter un peu avant les fêtes de Noël pour confirmation mais à priori ce sera ok pour nous

**Comment by MathildeDuboille** [comment]
Hello :) 

Je fais suite à notre thread de mail concernant le meetup de janvier. Nous aimerions savoir si le meetup sera virtuel ou non ?

Passe une bonne journée :)
Mathilde

**Comment by bloodyowl** [comment]
Hello 👋 

Le meetup sera en présentiel si les conditions sanitaires le permettent.

Si c'est cas et que c'est pas possible pour vous on pourra tenter une présentation en visio si la salle le permet.

**Comment by MathildeDuboille** [comment]
Hello :) 

Non justement on ne souhaiterait participer que si on peut être en présentiel, car c’est plus pratique pour nous :) 

Tenons-nous au courant

Passez de bonnes fêtes,
Mathilde

**Comment by bloodyowl** [comment]
Impeccable. 

Vous pouvez déjà marquer la date du 26 Janvier, on vous tient au courant dès qu'on a confirmé un lieu. 

Bonnes fêtes !

**Comment by Freddy03h** [comment]
Hello ! On est en train de relancer le meetup (again), est que vous êtes dispo pour donner ce talk le mercredi 30 mars ? Merci.

**Comment by Freddy03h** [comment]
@MathildeDuboille ?

**Comment by MathildeDuboille** [comment]
Sorry j'étais en congés ! Yes on est dispo le 30 mars :)

**Comment by Freddy03h** [comment]
Cool ! Je vous passe en validé alors !

**Comment by Freddy03h** [comment]
Hello @MathildeDuboille ! Est ce que toi et ton/ta collègue êtes bien inscrit•e•s sur l'évènement meetup ? C'est indispensable pour l'hôte https://www.meetup.com/fr-FR/Paris-js/events/284673204/
Merci

**Comment by MathildeDuboille** [comment]
Hello, c'est fait :)

**Comment by MathildeDuboille** [comment]
Hello @Freddy03h 
L'un de nous est positif au covid donc on ne pourra malheureusement pas participer au meetup de mercredi :/

**Comment by Freddy03h** [comment]
Ok, pas de soucis ! Est ce que vous seriez dispo le mercredi 27 avril pour le prochain meetup ?

**Comment by MathildeDuboille** [comment]
C'est mieux si on est deux oui :/ 
Dispo le 27 avril :)

**Comment by Freddy03h** [comment]
Hello @MathildeDuboille ! Est ce que tu peux me reconfirmer ta présence pour le meetup du 27 avril stp ? :)
Et de rejoindre le Discord aussi stp pour échanger plus facilement : https://discord.gg/c45mRqQg (ping moi quand tu y sera pour que je t'ajoute au channel privé de l'event)
Merci :)

**Comment by MathildeDuboille** [comment]
Toujours ok pour le 27 avril! Ca y est j'ai rejoins le discord au nom de Mathilde Duboille :)

**Comment by Freddy03h** [comment]
@Domino9697 Ok ^^
Au fait, tu peux rejoindre le discord aussi stp pour que je t'ajoute au channel privé de l'event ? Et je vais t'ajouter à la description meetup du talk aussi ! Merci.
