### ISSUE TITLE
TypeScript avancé: La genêse et conception de react-chicane

### ISSUE THREAD

**Issue by zoontek** [parisjs/talks#128]
## TypeScript avancé: La genêse et conception de react-chicane

*Talk format :* **Long** (20 min)

*Description :*

J'ai créé un nouveau routeur pour React. Pourquoi faire? `react-router` existe après tout.
Parce que contrairement à `react-router`, celui-ci s'enfonce très, très profondément dans le système de types de TypeScript (template literal types, types récursifs, mapped types, etc) et permet l'inférence de ce que l'on peut trouver dans l'url, mais aussi la création d'URL de façon safe

L'idée serait de dig progressivement dans la codebase en partant d'un type extrêmement simple pour finir sur une affreuseté absolue (voir https://github.com/zoontek/react-chicane/blob/main/src/types.ts#L59), en donnant au passage des exemples de comment appliquer ses notions avancées (mais de façon simple) au quotidien dans les codebases de chacun.

*Slides :* pas encore préparées
*Projet :* https://github.com/zoontek/react-chicane
*Twitter :* https://twitter.com/zoontek

**Comment by bloodyowl** [comment]
Hey @zoontek !

Tu serais dispo pour donner ce talk le 25 mai ?

**Comment by zoontek** [comment]
@bloodyowl Oui sans problème

**Comment by mauricesvay** [comment]
@zoontek est-ce que tes slides sont dispo quelque part ? J'aimerais les intégrer dans la vidéo

**Comment by zoontek** [comment]
@mauricesvay  oui ils sont là https://speakerdeck.com/zoontek/advanced-typescript-how-we-made-our-router-typesafe

**Comment by mauricesvay** [comment]
Merci !
