### ISSUE TITLE
Canceling long-running operations

### ISSUE THREAD

**Issue by Haroenv** [parisjs/talks#13]
## Canceling long-running operations

*Talk format :* Long

*Description :*

> A history of methods to handle asynchronous code in JS, options how to cancel them and what the future holds. Will touch on callbacks, Promises, AbortController and web workers.

*Slides :* undefined
*Projet :* undefined
*Twitter :* @haroenv

**Comment by PierrickP** [comment]
@Haroenv coucou, on fait un peu de nettoyage dans la liste. Est-ce que c'est un sujet que tu souhaites toujours présenter ?
Sinon tu peux close ;)
Merci
