### ISSUE TITLE
Lights, Camera, Action : Créer des vidéos en React.JS avec Remotion

### ISSUE THREAD

**Issue by jojmaht** [parisjs/talks#133]
## Lights, Camera, Action : Créer des vidéos en React.JS avec Remotion

*Talk format :* Long (~30 min)
  
*Description :*
  
> Lors du confinement, certain•es ont fait du pain, d'autres du sport, d'autres de la vidéo algorithmique.
> Dans ce talk, accompagné d'un livecoding, je souhaite présenter Remotion ainsi que certains concepts de creative coding, de mathématiques et de vidéo en général.

> Ce talk se veut relativement abordable à tout le monde et donc non-exhaustif.
  
*Slides :* Pas encore
*Projet :* Non plus
*Twitter :* @jojmaht

**Comment by mauricesvay** [comment]
@jojmaht Est-ce que tu peux partager tes slides ?
