### ISSUE TITLE
TS-Pattern: Bringing Pattern Matching to TypeScript

### ISSUE THREAD

**Issue by gvergnaud** [parisjs/talks#134]
## Bringing Pattern Matching to TypeScript

*Talk format :* Long

*Description :*

With the emergence and wide adoption of libraries such as React or XState, in the last few years the frontend ecosystem has shifted from an imperative to a declarative programming model. Now that we have realised how much easier it is to reason about declarative code and how many bugs are ruled out by embracing this paradigm, there is simply no going back.
Yet, Javascript and TypeScript weren’t designed for this paradigm, and these languages are lacking a very important piece of the puzzle: declarative code branching.

This talk will demonstrate how we can write conditional logic that is easy to read and maintain using ts-pattern, a Pattern Matching library for TypeScript.

*Projet :* https://github.com/gvergnaud/ts-pattern
*Twitter :* https://twitter.com/GabrielVergnaud

**Comment by Freddy03h** [comment]
Hello @gvergnaud  ! Est ce que tu serais dispo le mercredi 24 novembre pour nous proposer ton talk ? Merci 😀

**Comment by mauricesvay** [comment]
@gvergnaud Est-ce que tu peux partager tes slides ?
