### ISSUE TITLE
State machines en Front-End avec xState 

### ISSUE THREAD

**Issue by moh12594** [parisjs/talks#138]
## State machines en FrontEnd avec xState 

*Talk format :* Long
  
*Description :*
  
> Simplifier les logiques front-end (qui deviennent de plus en plus complexe aujourd'hui) peut-être un travail de longue haleine, surtout sur de grosses code bases. Chez Frichti, nous avons fait le choix d'utiliser xState (une librairie JS qui permet l'utilisation de state machines en front) afin de solidifier notre code base front, avoir une meilleure lisibilitée et un onboarding beaucoup plus clair pour les nouveaux devs. L'idée de la présentation est de vulgariser ce concept et donner quelques exemples réelles de l'utilisation de xState
  
*Slides :* https://slides.com/mohamedsadat/deck-e16d49
*Projet :* https://xstate.js.org/
*Twitter :* @AxelMSadat95

**Comment by bloodyowl** [comment]
Hello @moh12594!

Tu serais disponible pour donner ce talk à la prochaine édition du 25 mai ?

**Comment by moh12594** [comment]
Hello @bloodyowl ! 

Merci pour ta réponse, je ne serai malheureusement pas disponible le 25 mai mais pour les prochains, ce sera avec plaisir.

**Comment by bloodyowl** [comment]
Hello @moh12594!

Tu serais disponible pour l'édition du 22 juin prochain ?

**Comment by moh12594** [comment]
Hello @bloodyowl !
Yes, je suis disponible !
