### ISSUE TITLE
GraphQL & React-Admin : Exposer vos données en toute sérénité

### ISSUE THREAD

**Issue by Oupsla** [parisjs/talks#140]
## GraphQL & React-Admin : Exposer vos données en toute sérénité

*Talk format :* Long

*Description :* 

Dans la vie d'un projet il arrive un moment où l'on veut exposer ses données pour pouvoir les manipuler facilement mais sans donner accès en écriture à notre base de données à nos collègues non-tech.

Je vous propose de découvrir le super duo qu'est GraphQL, le très connu langage de requête, et React-admin, un framework basé sur React permettant de construire des interfaces d'administration en quelques lignes. Ayant gérer un schéma GraphQL pendant plusieurs années en production, je vous propose également dans ce talk de faire le tour des problèmes communs qu'on rencontre et comment les résoudre.

References
Construction du talk :

Présentation de GraphQL
Présentation de React Admin
Problèmes courants rencontrés avec GraphQL (N+1 problem, permissions, ...)

*Slides :* https://slides.com/oupsla/grapql-react-admin
*Projet :* -
*Twitter :* https://twitter.com/NDelpi

**Comment by Freddy03h** [comment]
Hello @Oupsla ! Est ce que tu serais dispo pour le meetup du 28 septembre ? merci !

**Comment by Oupsla** [comment]
Hello @Freddy03h, 
Pas dispo le 28 septembre malheureusement 😕 
Peut-être pour un prochain

**Comment by Freddy03h** [comment]
Merci de ta réponse, est ce que tu te déplaces parfois sur Paris ? Le prochain meetup serait le 26 octobre, est ce que c'est envisageable de ton côté ? Merci

**Comment by Freddy03h** [comment]
ping @Oupsla !
Est ce que tu serais dispo pour le meetup du 26 oct. ? ou celui du 30 nov. ?
Merci ^^

**Comment by Oupsla** [comment]
Oops désolé j'avais pas vu le précédent message !
A priori non pas dispo, désolé 😕 
Mes descentes sur Paris sont trop aléatoires pour prévoir un meetup, si jamais vous en organisez un en remote je suis dispo mais sinon tu peux archiver mon sujet je pense

**Comment by Freddy03h** [comment]
Ah mince dommage de pas pouvoir coïncider un passage sur Paris avec un meetup.
Malheureusement on ne prévoit pas de refaire de meetup online, du coup je vais close en effet.

N'hésites pas à ré-ouvrir si jamais tu peux faire correspondre un passage sur paname avec un meetup (on organise tous les derniers mercredi du mois) !

**Comment by Oupsla** [comment]
> N'hésites pas à ré-ouvrir si jamais tu peux faire correspondre un passage sur paname avec un meetup (on organise tous les derniers mercredi du mois) !

C'est noté !
