### ISSUE TITLE
Rust à la rescousse des performances de javascript

### ISSUE THREAD

**Issue by viconnex** [parisjs/talks#141]
## Rust à la rescousse des performances de javascript

*Talk format :* Long (20 min)

*Description :*

Un fond de carte dans un `canvas`. Un algorithme qui parcourt tous ses pixels. Une mosaïque en couleurs. C'est beau ! Mais que c'est lent... Grâce à `Rust` j'ai boosté les performances de calculs de pixels faits en front sur [maposaic.com](https://maposaic.com).

Je me suis vraiment éclaté en codant maposaic.com et je voudrais en partager les apprentissages :

- Introduction : description des premières optimisations faites sur le site (utilisation de Web Worker pour ne pas bloquer les interactions des utilisateurs)
- Description de l'algorithme de remplissage des pixels
- Pourquoi `Rust` se prête bien à ce cas : `Web Assembly` peut faire des calculs et les retourner au js.
- Comment se lancer dans `Rust` : la doc et le tutoriel sont très bien faits ; le lien avec javascript grâce à `wasm-bindgen`
- Zoom sur le code : présentation de la dev expérience (auto-complétion, détection d'erreurs à la volée)
- Comment la communauté rust sur reddit m’a aidé à optimiser le programme
- Conclusion : lancez-vous, c'est facile !

*Slides :* c'est la v2 du [talk de nantejs](https://www.youtube.com/watch?v=IsRPxvxL9a0) - cette présentation sera plus axée sur Rust.
*Projet :* https://maposaic.com
*Twitter :* https://twitter.com/viconnex

<img width="1635" alt="lille" src="https://user-images.githubusercontent.com/22373097/152704362-99047d83-0f21-458e-bbc9-a20554841e94.png">

**Comment by bloodyowl** [comment]
hello @viconnex!

tu serais disponible pour donner ce talk à l'édition du 30 novembre ?

**Comment by bloodyowl** [comment]
Erratum: planning complet pour le 30 novembre, serais-tu disponible pour l'édition du 25 Janvier ?

**Comment by viconnex** [comment]
Salut @bloodyowl dsl j'ai pas vu ton message. J'ai déjà fait [ce talk](https://github.com/parisjs/talks/issues/113) (le même sujet, moins axé rust), tu avais vu ? Je pense pas re-programmer de talk tout de suite donc je ferme l'issue.
