### ISSUE TITLE
Design système: Complexifier vos composants sans mettre la pagaille

### ISSUE THREAD

**Issue by alexfauquette** [parisjs/talks#144]
## Design système: Complexifier vos composants sans mettre la pagaille

*Talk format :* Long (20 min)

*Description :*

> Vous avez codé des composants incroyable, mais à force d'ajouter des options pour le customiser son api est devenu un enfert à utiliser et à maintenir?
> Venez avec moi faire un tour d'horizon des startégies mises en places par MUI pour créer des composants customizable et complexe  

*Slides :* WIP
*Projet :* https://mui.com/x
*Twitter :* https://twitter.com/AleFauquette

**Comment by bloodyowl** [comment]
Ah cool ! Ce serait top 👍
