### ISSUE TITLE
V8 by night, dans les secrets du moteur JS

### ISSUE THREAD

**Issue by vdeturckheim** [parisjs/talks#147]
## V8 by night, dans les secrets du moteur JS

*Talk format :* Long (20 min)

*Description :*

Tu connais V8? C'est le moteur JavaScript qui fait tourner Chrome, Node.js et bien d'autres. Tu l'utilises probablement au quotidien. Mais tu t'es déjà demandé comment le moteur faisait pour executer le code si rapidement? Bon, bah moi oui!

Dans ce talk, je vais te parler de comment V8 fait pour gérer la mémoire ou executer et optimiser le code. Je vais aussi te parler de fonctionnalités plus ou moins secretes de V8 (enfin les trucs que la team V8 aime pas qu'on bidouille). On va même voir comment le debugger marche sous le capot!
Ce talk va te donner des outils pour auditer comment ton code tourne et prendre les bonne décisions dans tes projets.

**Comment by bloodyowl** [comment]
Hey @vdeturckheim!

Tu serais dispo pour donner ce talk le 25 mai ?

**Comment by vdeturckheim** [comment]
@bloodyowl yes!
