### ISSUE TITLE
Automate everything via NodeJS and Puppeteer

### ISSUE THREAD

**Issue by TheJoin95** [parisjs/talks#149]
## Automate everything via NodeJS and Puppeteer

*Talk format :* Long

*Description :*

Automation is the key. I've developed a lot of tool using NodeJS and Puppeteer as stack in order to automate a process, a test, a human task.

In this talk I'm gonna do a brief introduction to the topic and talk about personal & professional expérience:
 - automate a video to audio conversion from YouTube to Anchor.fm
 - automate the scan of a flight in order to book a holiday

Note: the talk will be in English 
  
*Slides :* [gdrive slides](https://docs.google.com/presentation/d/1N8JI5hyKgmRMFYHFJPoW3DKF1hIisaVh38ILWZFJw60/edit?usp=sharing)
*Twitter :* [thejoin95](https://twitter.com/thejoin95)

**Comment by bloodyowl** [comment]
hello @TheJoin95 !

which of the following dates would work best for you:
- 29 March
- 26 April
- 31 May

?

**Comment by TheJoin95** [comment]
Hi there,

not sure about doing this talk, may I come back to you with a date and another talk?
I was thinking on proposing an experience about the development of https://github.com/Schrodinger-Hat/open-source-wrapped and eventually have a co-speaker.

At this stage, I'm more oriented on the 26 April, thanks
