### ISSUE TITLE
V8 : Master Garbage Collector

### ISSUE THREAD

**Issue by wallet77** [parisjs/talks#15]
## V8 : Master Garbage Collector

*Talk format :* Long

*Description :*

> Le moteur V8 c'est un peu la magie de l'execution de javascript, côté client (chrome) et côté serveur (nodejs). Il gère pour vous la gestion de la mémoire grâce à son garbage collector !
> Pourquoi un garbage collector dans V8 ?
> Comprendre comment il fonctionne, quand il passe et pourquoi.
> Comment optimiser son code pour ne pas créer de problème lié à la mémoire.
> Comment le monitorer et obtenir des informations.

*Slides :* undefined
*Projet :* undefined
*Twitter :* @Vince_Vallet

**Comment by wallet77** [comment]
Hello les amis,

Des news sur la programmation (ou pas) de ce talk ?
Pour infos les slides (non définitives) sont ici : https://docs.google.com/presentation/d/17PXOZXBgdJHqBZlbULHg70_hVFLrNx9T34rB9bLDn2M/edit?usp=sharing

**Comment by Freddy03h** [comment]
Hello @wallet77 est ce que tu es dispo le mercredi 24 octobre pour présenter ton talk au ParisJS#78 ?
Désolé de te prévenir un peu tard.

**Comment by wallet77** [comment]
Hello @Freddy03h 

Ca doit être bon pour moi à cette date là ;)

**Comment by Freddy03h** [comment]
Top !

**Comment by wallet77** [comment]
Les amis,

J'ai vu que le talk était déjà plein, mais c'est possible d'avoir deux places pour des invités ?

**Comment by PierrickP** [comment]
@wallet77 envoi moi les nom/prenoms sur twitter/slack en dm, je vais les ajouter

**Comment by wallet77** [comment]
Salut @Freddy03h ,

J'ai vu avec Pierrick pour ajouter deux personnes en guests pour le talk de mercredi.
Dis moi si c'est toujours possible de les ajouter à la liste.

Voici les noms : 
Aymeric Roffé
Robin Mizreh

A mercredi.

**Comment by Freddy03h** [comment]
J'ai ajouté Aymeric mais je ne trouve pas Robin, il a un pseudo ?

**Comment by wallet77** [comment]
Pas sûr non.
