### ISSUE TITLE
Réduire l'impact carbone de ses servers grâce au Serverless

### ISSUE THREAD

**Issue by MaximeThoonsen** [parisjs/talks#152]
## Réduire l'impact carbone de ses serveurs grâce au Serverless

**Talk format :** Long
  
**Description :**
 
 Malgré l'explosion du traffic sur internet durant la dernière décennie, la consommation des datacenters n'a que faiblement augmenté. Nous verrons dans ce talk les principales sources de consommation d'énergie dans les serveurs et comment le Serverless peut aider à réduire cette consommation
  
**Slides :** https://docs.google.com/presentation/d/1OGBDYRMg7Fvde_inosmOXFE5hSYb5oLKgPQJOhuMCM4/edit#slide=id.gd6134b9547_0_0

**Twitter :** @maxthoon

**Comment by bloodyowl** [comment]
hello @MaximeThoonsen!

tu serais dispo pour donner ce talk pour l'édition du 26 octobre ?

**Comment by MaximeThoonsen** [comment]
Hello @bloodyowl ,
Pas possible pour moi pour cette édition malheureusement. Mais chaud pour celle d'après si vous avez déjà la date ?

**Comment by bloodyowl** [comment]
Yes, la suivante sera le 30 Novembre. Ça t'irait ?

**Comment by MaximeThoonsen** [comment]
@bloodyowl ok très bien
