### ISSUE TITLE
L'art délicat de la review

### ISSUE THREAD

**Issue by Strato** [parisjs/talks#153]
## L'art délicat de la review

    *Talk format :* Long
  
    *Description :*
  
    > Talk sur pourquoi et comment faire de reviews, un sujet pas si évident dont on ne parle pas souvent et les soft skills c'est aussi important.

> C'est plutôt prévu pour du 40 minutes mais je peux l'écourter (je parle aussi de CI et je fais un peu l'historique des contrôleurs de source).

> Je travaille encore dessus mais je devais le finaliser pour la fin du mois de toute façon.
  
    *Slides :* https://docs.google.com/presentation/d/122buEXfE26n-LGkFoyW9u9AwU3me4_dhsLfYROJL7qw/edit?usp=sharing
    *Projet :* 
    *Twitter :*

**Comment by Freddy03h** [comment]
Hello @Strato ! Est ce que tu serais dispo pour le meetup du 28 septembre ? merci !

**Comment by Strato** [comment]
Oui je suis dispo. 👍

> Hello @Strato ! Est ce que tu serais dispo pour le meetup du 28 septembre ? merci !

Oui je suis dispo. 👍

**Comment by Freddy03h** [comment]
Ok merci @Strato alors je te confirme pour le meetup 101 du 28 septembre ;)
