### ISSUE TITLE
Comment charmer Googlebot avec ton application NextJS

### ISSUE THREAD

**Issue by alexandrepernin** [parisjs/talks#155]
## Titre de la présentation

*Talk format :* Long (20 min)

*Description :*

L’architecture frontend en Single-Page-Application, bien que très populaire ces dernières années, pose problème pour le référencement (SEO). Les frameworks de rendu côté serveur (SSR) permettent de surmonter ces limitations. 

C’est ce que propose NextJS, la surcouche de React. Malgré tout, quelques bonnes pratiques relatives à ce framework méritent d’être connues pour hisser son site en pole position de la recherche Google.

Dans ce talk, je résumerai les apprentissages générés sur trois projets NextJS à forte attente SEO réalisés en tant que Tech Lead chez Theodo. J’aborderai successivement les points suivants : 

- Crawling et indexing : le fonctionnement de Googlebot
- Les informations à fournir absolument au crawler
- Les différents modes de rendu NextJS
- Bonnes pratiques NextJS pour optimiser son référencement

A la fin de ce talk, vous saurez pourquoi et comment bien utiliser un framework de rendu côté serveur sur votre prochain projet à besoin SEO.

*Slides :* WIP

**Comment by bloodyowl** [comment]
hello @alexandrepernin!

tu serais disponible pour présenter ce talk le 30 novembre ?

**Comment by bloodyowl** [comment]
Erratum: planning complet pour le 30 novembre, serais-tu disponible pour l'édition du 25 Janvier ?

**Comment by alexandrepernin** [comment]
Hello ! Oui c'est ok pour moi :) Merci beaucoup !

**Comment by alexandrepernin** [comment]
Hello @bloodyowl, c'est bien confirmé pour le 25 Janvier ?

**Comment by bloodyowl** [comment]
hello @alexandrepernin!

mauvaise nouvelle, on a une galère d'organisation sur la salle et on risque de décaler au 1er Février. ce serait ok pour toi ?

**Comment by alexandrepernin** [comment]
Hello ! 
Yes ok pour moi mercredi 01/02, tu pourras me confirmer ici quand c'est définitif ? mercii

**Comment by bloodyowl** [comment]
c'est confirmé @alexandrepernin! https://www.meetup.com/paris-js/events/291181025/?isFirstPublish=true

**Comment by alexandrepernin** [comment]
c'est bien noté ! à mercredi :)
