### ISSUE TITLE
Pas besoin de serveur pour les avatars

### ISSUE THREAD

**Issue by laurentpayot** [parisjs/talks#157]
### Format

Lightning (5 minutes)

### Description

[Minidenticons](https://github.com/laurentpayot/minidenticons#readme), un paquet qui permet de générer des identicônes (avatars pixelisés) côté client à partir des noms d’utilisateurs, au lieu de télécharger des images d’un serveur. En quelques lignes de code seulement.

### Autre

Des slides sont-ils obligatoires pour un *lightning talk* ? Puis-je simplement utiliser ma [démo en ligne](https://laurentpayot.github.io/minidenticons/) et quelques pages web ?

**Comment by Freddy03h** [comment]
Non pas besoin de slides pour un lightning, l'important c'est de tenir en 5 min ^^

Tu serais dispo pour le prochain meetup le 26 oct. ? sinon 30 nov. ?

**Comment by laurentpayot** [comment]
@Freddy03h  Le 26 c’est parfait, je comptais déjà venir en tant que spectateur. En plus ce petit *talk* est complémentaire de celui sur les "Offline Web Apps".

Je prépare tout ça alors. À mercredi !
