### ISSUE TITLE
Détecter les race-conditions dans vos applications JavaScript

### ISSUE THREAD

**Issue by dubzzz** [parisjs/talks#159]
### Format

Long (20 minutes)

### Description

Les race-conditions sont souvent un problème sous estimé en JavaScript, pourtant par nature elles sont potentiellement omniprésentes. Cependant les détecter et comprendre est souvent un véritable parcours.

Ce talk a plusieurs missions allant de expliquer ce que sont ces "race-conditions", où on les trouve basé sur des cas réels connus mais surtout tente de donner des outils pour vous aider à les trouver.

### Lien vers vos slides

https://dubzzz.github.io/talk-react-europe-2020/slides/

### Autre

Les slides sont là à titre indicatif, je vais surement les adapter un peu pour les besoins du talk.

### Twitter

ndubien

### Email

github@dubien.org

**Comment by bloodyowl** [comment]
hey @dubzzz!

tu serais dispo pour donner ce talk le 30 novembre ?

**Comment by dubzzz** [comment]
Je regarde ça dans la semaine, je reviens vers vous dans le courant de la semaine

**Comment by dubzzz** [comment]
Hey @bloodyowl,

Merci beaucoup pour la proposition, malheureusement, ça ne sera pas possible pour moi le 30 Novembre (je ne serai pas sur Paris à ce moment là).

L'édition suivante sera le 25 Janvier 2023, c'est bien ça ? Si la proposition tient encore, je serai là en Janvier.

**Comment by bloodyowl** [comment]
hello!

yes, exactement! je te programme pour Janvier.

**Comment by dubzzz** [comment]
Merci beaucoup :) Parfait pour Janvier

**Comment by dubzzz** [comment]
@bloodyowl, juste pour confirmer, c'est toujours ok pour le 25 Janvier ?

**Comment by bloodyowl** [comment]
hello ! yes c'est toujours d'actualité !

**Comment by bloodyowl** [comment]
hello @dubzzz!

mauvaise nouvelle, on a une galère d'organisation sur la salle et on risque de décaler au 1er Février. ce serait ok pour toi ?

**Comment by dubzzz** [comment]
Hello,
Je ne pourrai malheureusement pas le 1er Février, je ne serai plus sur Paris.
Une prochaine fois 👍

**Comment by dubzzz** [comment]
Hello @bloodyowl,
Sorry pour cette fois. Si c'est toujours ok pour le talk, je devrai pouvoir être sur Paris le Mercredi 22 Février pour la prochaine édition.

**Comment by dubzzz** [comment]
Hey @bloodyowl, any update?

**Comment by bloodyowl** [comment]
hello @dubzzz,

parfait, je te mets au programme pour le 22 !

**Comment by dubzzz** [comment]
Je te confirme rapidement ma dispo, je dois encore book un billet de train pour monter à Paris.

**Comment by dubzzz** [comment]
Ca sera good pour moi, on se voit le 22 👍
