### ISSUE TITLE
Machine learning <3 JS : rendez votre navigateur web intelligent

### ISSUE THREAD

**Issue by antamb** [parisjs/talks#16]
## Machine learning ♥ JS : rendez votre navigateur web intelligent

*Talk format :* Long

*Description :*

> Faire du machine learning n'est plus seulement réservé aux charmeurs de serpents (pythonistas) ou à ceux ayant accès à des machines puissantes. Dans le cadre du projet PAIR, l'équipe Brain de Google sortait la librairie deeplearn.js qui a depuis lors évolué pour laisser place à TensorFlow.js. Tensorflow.js se base sur WebGL et permet entre autres de construire et d'entrainer des modèles de données dans le navigateur "from scratch" ou en utilisant des techniques telles que le "transfer learning".

> Je vous expliquerai durant ce talk comment nous avons développé une PWA "intélligente" en utilisant du machine learning.

*Slides :* undefined
*Projet :* undefined
*Twitter :* @AidaraAnta

**Comment by antamb** [comment]
@PierrickP Hello, oui je serai dispo

**Comment by PierrickP** [comment]
@antamb Super !
J'ai fait un brouillon de meetup, ca part quand j'ai la confirmation de l'hote

**Comment by antamb** [comment]
Ok ça marche!

**Comment by PierrickP** [comment]
Bonjour Anta,

Paris.js est partenaire de http://bestofweb.paris (et je suis dans l'orga).
Pour rappel, c'est une conference d'un jour à Paris, organisée par des bénévoles.
Le programme est un mix des meilleurs sujets des meetups Parisiens et d'un CFP.

Nous avons sélectionné ton talk en *bestof* de Paris.js ✨ !

Serait-tu intéressée de le re-présenter le 7 Juin 2019 ?

Hésite pas si tu as la moindre question, ici ou par mail hello@pierrickp.xyz
Merci
