### ISSUE TITLE
What happens when you build your react-native app

### ISSUE THREAD

**Issue by charlotteisambert** [parisjs/talks#160]
### Format

Long (20 minutes)

### Description

Let’s check out together what a React Native app looks like under the hood. And especially, let's take a look at what happens when we build it.
We’ll identify the shortest steps to execute daily actions in our mobile world, like starting our apps as fast as possible, or dealing with pesky red errors that metro throws at us.

### Lien vers vos slides

https://user-images.githubusercontent.com/34058526/169569616-94b202f5-12e0-468e-be65-92e03bbfb2ec.png

### Autre

Voici une autre de mes slides :) 
https://user-images.githubusercontent.com/34058526/199527516-8bf32c1d-acd9-4604-ad6f-95274327214f.png

### Twitter

https://twitter.com/c_isambert

**Comment by bloodyowl** [comment]
hello @charlotteisambert!

tu serais disponible pour présenter ce talk le 30 novembre ?

**Comment by charlotteisambert** [comment]
Hello @bloodyowl !

Oui je suis dispo 😊
