### ISSUE TITLE
Les 5 headers de sécurité à connaître

### ISSUE THREAD

**Issue by BenoitSerrano** [parisjs/talks#161]
### Format

Long (20 minutes)

### Description

Content-Security-Policy, Referrer-Policy, Strict-Transport-Security... Vous avez forcément déjà vu ces noms, sans être bien sûr de comprendre à quoi ils servent.  Pourtant, ils sont très simples à implémenter et offrent une protection robuste contre les attaques web classiques !

### Lien vers vos slides

https://docs.google.com/presentation/d/1-y4LPgmnaZjnrsp22qFMuErU94ImyIhsZYr-sotyY4g/edit?usp=sharing

### Twitter

@Serrano_Benoit

### Email

benoit.serrano10@gmail.com

**Comment by bloodyowl** [comment]
hello @BenoitSerrano!

tu serais disponible pour donner ce talk à l'édition du 30 novembre ?

**Comment by BenoitSerrano** [comment]
Hey @bloodyowl 

Tout à fait dispo le 30 novembre pour donner ce talk oui !

**Comment by bloodyowl** [comment]
top, merci beaucoup !
