### ISSUE TITLE
Pourquoi le CSS Ca Saoule Souvent

### ISSUE THREAD

**Issue by AlbericTrancart** [parisjs/talks#162]
### Format

Long (20 minutes)

### Description

Tu t’es déjà senti frustré·e par le CSS ? Que ce soit pour centrer les choses verticalement ou utiliser des hacks magiques pour obtenir ce qu’on veut… soit on a le “gène CSS”, soit on ne l’a pas. Les devs qui aiment le CSS semblent plus être l’exception que la règle.
Mais n’aie pas peur ! Ce n’est pas une fatalité.
Après avoir formé des douzaines de développeurs à CSS sur les 5 dernières années, j’ai fini par comprendre ce qui n’allait fondamentalement pas avec le CSS. Et je suis prêt à te le partager.

### Lien vers vos slides

https://slides.com/alberic/pourquoi-le-css-ca-saoule-souvent/

### Autre

J'ai déjà présenté ce talk aux HumanTalks Paris de novembre, l'idée serait de faire une version plus longue que 10min et d'avoir un public différent :) 

### Twitter

alberictrancart

**Comment by bloodyowl** [comment]
hello @AlbericTrancart 👋

tu serais dispo pour donner ce talk à l'édition du 22 Février ?

**Comment by AlbericTrancart** [comment]
Salut @bloodyowl , yep je suis dispo !

**Comment by bloodyowl** [comment]
top! see you there!
