### ISSUE TITLE
Finding performance bottlenecks with OpenTelemetry

### ISSUE THREAD

**Issue by larskarbo** [parisjs/talks#163]
### Format

Long (20 minutes)

### Description

Quand tu commences à avoir des utilisateurs, la performance dans une application Node.js devient de plus en plus importante.

Souvent, c'est difficile de savoir où sont exactement les goulots d'étranglement de performance. Est-ce que c'est le serveur de l'application ou la base de données? Est-ce que c'est les DB queries qui sont lents ? Quelle route HTTP a des problèmes ? Est-ce que un CDN peut aider ?

À Layer3, nouse avons eu des problèmes de performance quand nous avons eu des pics de trafic.

Le breakthrough est venu quand nous avons implémenté OpenTelemetry et le tracing. Ce qui avait besoin d'être optimiser dans l'application, nous est alors paru tout de suite évident.

J'aimerais expliquer comment nous l'avons implémenté dans notre code base (c'est pas beaucoup de travail), et comment nous avons utilisé la data pour faire des optimisations.

![shot-Gnqr5sbk](https://user-images.githubusercontent.com/10865165/205276699-bc6d9ff6-31dc-4042-8f0e-aa1c603a7f54.png)

### Lien vers vos slides

https://docs.google.com/presentation/d/1DXEtlZElicfH0BwCgpmZICX7gH2f_p_Md6-MUg2dY84/edit#slide=id.p

### Twitter

https://twitter.com/larskarbo

### Email

mail@larskarbo.no

**Comment by bloodyowl** [comment]
hello @larskarbo!

tu serais disponible pour présenter ce talk à l'édition du 25 janvier ?

**Comment by larskarbo** [comment]
Oui!

**Comment by bloodyowl** [comment]
trop cool, merci de ta réponse !

**Comment by larskarbo** [comment]
C'est où et quand le meetup? @bloodyowl

**Comment by bloodyowl** [comment]
hello @larskarbo!

désolé du délai on a mis un peu de temps à sécuriser un lieu! ce sera le 25 à 19h chez Meilleurs Agents au 7 boulevard Haussman, 75009 Paris

**Comment by bloodyowl** [comment]
hello @larskarbo !

finalement, mauvaise nouvelle, on a encore une galère d'organisation sur la salle et on risque de décaler au 1er Février. ce serait ok pour toi ?

**Comment by larskarbo** [comment]
@bloodyowl pas de souci, 1er Février peut aller aussi pour moi!
