### ISSUE TITLE
Workflow automation with Nodejs

### ISSUE THREAD

**Issue by hauld** [parisjs/talks#164]
### Format

Long (20 minutes)

### Description

Experiment design of event driven workflow engine in NodeJs:
- Task queue based on BTree data structure
- Task controller based on Event Emitter
- Task executor based on Worker Thread
- Simple demo with flow scripting

### Lien vers vos slides

https://www.canva.com/design/DAFU1mXjoEk/oLVhsdsCwxDb5iTdDk6S-w/view?utm_content=DAFU1mXjoEk&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink

**Comment by bloodyowl** [comment]
hello @hauld 👋

are you available on Feb 22 to give this talk at Paris.JS?

**Comment by bloodyowl** [comment]
let's go for March then! are you available on the 29?

**Comment by hauld** [comment]
Yes I am. I will block my calendar for 29 Mar.
