### ISSUE TITLE
Prenez la bonne décision en rédigeant un ADR

### ISSUE THREAD

**Issue by GrenardAntoine** [parisjs/talks#167]
### Format

Long (20 minutes)

### Description

Dans notre quotidien de développeur il nous arrive souvent d’enfiler notre casquette d’archéologue et d’aller étudier une base de code, une architecture ou un structures de base de donnée écrite dans des temps immémoriaux.

En ouvrant ce tombeaux du code scellé depuis des temps ancestraux - le pot de départ de Jimmy de novembre dernier - nous allons déclencher le retour d’une des plus anciennes et des pire des malédiction de l’ingénierie : Le retour du  “BUT WHY DID THEY DO THAT ?”

Bien plus qu’une solution de documentation je vous propose une méthodologie permettant à l’écriture de la documentation elle même de vous faire prendre de meilleures décision.

Je suis sûr d’avoir pris la bonne décision avant même de poser ma première ligne de code. Et vous ?

### Email

grenard.antoine@gmail.com

**Comment by bloodyowl** [comment]
hello @GrenardAntoine !

tu serais disponible pour donner ce talk à l'édition du 26 avril ?

**Comment by GrenardAntoine** [comment]
Hello @bloodyowl,

Super, je suis disponible à cette date ! 
Je recevrais la suite des infos par quel biais ? (mail ? github ? téléphone)

**Comment by bloodyowl** [comment]
hello, cool !

ce sera soit ici soit par mail, comme tu préfères

**Comment by GrenardAntoine** [comment]
Par mail c'est très bien :)
