### ISSUE TITLE
Une histoire du temps : Comment, en 2015, internet a cassé en 1 seconde

### ISSUE THREAD

**Issue by Gguigre** [parisjs/talks#168]
### Format

Long (20 minutes)

### Description

**[Partie 1] Historique**
Comment a-t-on construit la conception moderne du temps ? Et comment faire pour que tout le monde s'accorde sur la même heure.

**[Partie 2] Existant**
Qu'est-ce que la norme ISO-8601 et quels sont les différents cas atypiques que l'on peut rencontrer

**[Bonus] Tech**
Quelle solution sur vos projets ? 

### Lien vers vos slides

https://docs.google.com/presentation/d/13fI-AM3rz5IauiRo6v8rPzF2rPZpGbe9O3KL4gUfuI0/edit?usp=sharing

### Autre

J'ai aussi une video de la formation donnée en interne dans mon entreprise : https://drive.google.com/file/d/1MHyg10nPC7inB56eTtgdQudQ34CCWTLF/view?usp=sharing

### Email

guillaumeg@bam.tech

**Comment by bloodyowl** [comment]
hello @Gguigre!

tu serais disponible pour donner ce talk à l'édition du ~~29 mars~~ 26 avril ?

**Comment by Gguigre** [comment]
Hello @bloodyowl yes c'est bon pour moi le 26 avril, avec plaisir !
