### ISSUE TITLE
Comment connecter 1980 et 2018 avec une extension Chrome et Chrome Native Messaging

### ISSUE THREAD

**Issue by matthieukern** [parisjs/talks#17]
## Comment connecter 1980 et 2018 avec une extension Chrome et Chrome Native Messaging

*Talk format :* Long

*Description :*

> Chez Doctolib, nous avons à nous interfacer avec des logiciels allant du site web en SAAS au logiciel natif développé en 1980. Presqu'aucun de ces logiciels n'est prévu pour la communication avec d'autres outils. Nous avons mis en place une architecture multi couches articulée autour d'une extension Chrome : injection d'une API javascript dans les pages de nos partenaires ou lancement d'un binaire avec Chrome Native messaging pour communiquer avec des logiciels installés directement sur le poste de nos clients.

> Nous présenterons au cours de ce talk la manière de créer une extension Chrome permettant de réaliser ce type d'actions. Nous parlerons ensuite du déploiement de binaires sur les postes clients en utilisant un Node.JS embarqué (PKG), communiquant avec un site web au travers de Chrome Native Messaging.

*Slides :* undefined
*Projet :* undefined
*Twitter :* undefined

Nous comptons effectuer ce talk à deux speakers avec @qmenoret

**Comment by PierrickP** [comment]
:warning: Idéalement à faire chez eux, ils nous accueil :)
