### ISSUE TITLE
Le filtre de Kalman : pourquoi et comment ?

### ISSUE THREAD

**Issue by piercus** [parisjs/talks#173]
### Format

Long (20 minutes)

### Description

![demo_light](https://user-images.githubusercontent.com/156736/228787967-8336e8d7-b7fc-484a-a047-c423b252e7a4.gif)

Le talk a pour but de présenter la librairie https://github.com/piercus/kalman-filter

1. Qu'est ce que le Kalman Filter, à quoi ca sert ? 

2. Un exemple simple de filtre Kalman en JS : modéliser la chute d'une moto
Les modèles dynamiques/observationnels implémentés

3. Pourquoi faire cela en JS et non en Python ?
  a. Sur ce type de sujet, Python est LA référence avec matlab 
  b. L'avantages de python : numpy + la communauté
  c. Pourquoi le JS : le polymorphisme et les applications front (le RLHF)

### Twitter

piercus

### Email

piercus@gmail.com

**Comment by bloodyowl** [comment]
hello @piercus! tu serais disponible pour donner ce talk le 31 mai ?

**Comment by piercus** [comment]
Oui, avec plaisir !
