### ISSUE TITLE
6 Tips pour améliorer sa Web App Angular

### ISSUE THREAD

**Issue by camillepillot** [parisjs/talks#177]
### Format

Long (20 minutes)

### Description

Si Angular est d’apparence plus simple à découvrir (merci les tutos Google), il est probablement plus complexe à maîtriser que ses comparses. Dans ce talk, je vous propose 6 tips qui ont changé la donne dans le code de nos apps, que ce soit en termes de performances ou de lisibilité. 

### Lien vers vos slides

https://github.com/camillepillot/angular-tips/blob/main/Angular%20TIPS%20version%20pdf.pdf

### Autre

Les slides sont élargis avec des screens de demo/video expliquées pour le format pdf mais lors du talk ce seront de vraies démos

### Twitter

@camiPillotDev

### Email

cpillot@takima.fr

**Comment by bloodyowl** [comment]
hello!

tu serais disponible pour donner ce talk à l'édition du 28 juin ?

**Comment by camillepillot** [comment]
Salut ! 

Je ne suis pas disponible le 28 juin, j'espere pour une édition suivante ? 😄

**Comment by bloodyowl** [comment]
hello @camillepillot, tu serais disponible pour donner ce talk à l'édition du 25 octobre ?

**Comment by camillepillot** [comment]
hello, j'étais en vacances désolé, j'ai fermé la proposition car je pense qu'il commence a etre 'vieux' avec l'arrivée d'angular 17 la semaine pro 😞
