### ISSUE TITLE
Modern services communication with gRPC

### ISSUE THREAD

**Issue by zoontek** [parisjs/talks#18]
## Modern services communication with gRPC

*Talk format :* Long

*Description :*

> Une présentation de gRPC + protobuf pour architecturer ses microservices, avec une petite démo en nodeJS et une petit clin d'oeil à GraphQL

*Slides :* undefined
*Projet :* undefined
*Twitter :* @zoontek

**Comment by PierrickP** [comment]
:warning: a faire en mai chez Scaleway ;)

**Comment by PierrickP** [comment]
Si tu as les slides, je suis preneur !

**Comment by PierrickP** [comment]
tu as pas une version lisible en ligne ? (meme un export pdf)

**Comment by zoontek** [comment]
C'est en cours de processing sur Speakerdesk, je t'envoie le lient après :)

**Comment by zoontek** [comment]
Voilà: https://speakerdeck.com/zoontek/manage-microservices-like-a-chef :)

**Comment by PierrickP** [comment]
Coucou

Paris.js est partenaire de http://bestofweb.paris (et je suis dans l'orga).
Pour rappel, c'est une conférence d'un jour à Paris, organisée par des bénévoles.
Le programme est un mix des meilleurs sujets des meetups Parisiens et d'un CFP.

Nous avons sélectionné ton talk en *bestof* de Paris.js ✨ !

Serait-tu intéressé de le re-présenter le 7 Juin 2019 ?
L'autre jour tu me parlais d'un concurrent à Protobuf, si tu veux légèrement modifier le sujet, c'est possible.

Hésite pas si tu as la moindre question, ici ou par mail hello@pierrickp.xyz
Merci

**Comment by zoontek** [comment]
Salut Pierrick,

Avec joie!
Flatbuffers étant supporté de base par gRPC, aucun souci pour l'inclure dans le talk 🙂

Mathieu

**Comment by PierrickP** [comment]
awesome !
Je crois pas avoir ton mail, tu peux me l'envoyer ?

**Comment by zoontek** [comment]
C’est zoontek@gmail.com

Mathieu
