### ISSUE TITLE
Comment améliorer vos tests front avec Testing Library

### ISSUE THREAD

**Issue by elisere** [parisjs/talks#180]
### Format

Long (20 minutes)

### Description

85% de test coverage sur le front ça semble plutôt satisfaisant. Mais peut être qu’ils sont difficiles à écrire, à maintenir. Peut être même que les devs râlent dès qu’ils doivent écrire des tests. Qui n’a jamais eu envie, même pendant une seconde, de laisser tomber les tests ? En partant de mon expérience d’utilisation de Testing Library sur de multiples projets, je partagerai plusieurs apprentissages sur la mise en place des tests front. Au programme :

- présentation de Testing Library
- bonnes pratiques de test (niveau de scoping des tests, abstraction à l’implémentation, tests d’accessibilité … )
- comment former et sensibiliser les devs

Après ce talk vous aurez des astuces concrètes pour améliorer vos tests front.

### Autre

Bonjour,
Je ne suis pas disponible pour la session de juin mais j'aimerais postuler pour celle de septembre
Merci beaucoup

### Email

eliser@theodo.fr

**Comment by bloodyowl** [comment]
hello!

je te programme pour le 27 septembre du coup, good pour toi ?

**Comment by elisere** [comment]
Hello ! Yes carrément ! Merci !!

Le lun. 5 juin 2023, 12:06, Matthias Le Brun ***@***.***> a
écrit :
