### ISSUE TITLE
REX :notes:  : Trouver des bugs... en améliorant les perfs

### ISSUE THREAD

**Issue by sebsheep** [parisjs/talks#186]
### Format

Long (20 minutes)

### Description

On a tous eu ce genres de réflexions :
"Tiens, tiens, cette requête HTTP est un peu lente :turtle:  . Il faudra que je regarde ça. Un jour..."

"Ah ah ! Avec ce client et ces 40 000 personnes, cette route met tellement de temps à répondre que Ngnix renvoie une '504 Gateway Timeout' :clock1:  . Il faudra que je regarde ça. Un jour..."

Et puis le "jour" est venu ! Et, oh surprise !, l'amélioration de ces performances casse les tests ! Pourtant, on n'a rien touché à la logique correspondant à ces tests... :thinking: 

À travers ce retour d'expérience, on parlera temps de réponses, JWT, compléxité algorithmique et tries prefixes. Et on râlera sur "ce client" avec ces 40 000 personnes.

### Twitter

`_sebbes_`

### Email

je suis sur le slack paris js (Sébastien Besnier)

**Comment by bloodyowl** [comment]
hello @sebsheep, tu serais disponible pour donner ce talk à l'édition du 25 octobre ?

**Comment by sebsheep** [comment]
Salut ! Merci de la proposition, mais je serai en congé à l'autre bout de la France :) . Au mois du novembre, ça me paraît jouable par contre.

**Comment by sebsheep** [comment]
@bloodyowl j'ai vu la notif du nouvel événement par mail... J'ai été un peu surpris car tu ne m'avais pas confirmé avant. Ça tombe bien pour cette fois, même si du coup je n'ai qu'une semaine pour préparer les slides...
