### ISSUE TITLE
Comment fonctionnent les server components de React 18 - s'en servir avec Next 13

### ISSUE THREAD

**Issue by raphaelbadia** [parisjs/talks#188]
### Format

Long (20 minutes)

### Description

Pour le meilleur ou pour le pire, les "server components" de react sont là... et il faut s'y adapter !

Dans ce talk, nous verrons pourquoi les server components ont été inventé par la team react, quels problèmes ils cherchent à résoudre et comme le modèle mental évolue par rapport à "l'ancien" react.

Je montrerai des avant/après de cas concrets de migrations que j'ai effectué, et je parlerai des nouveaux problèmes (de sécurité, et de tooling) que cette mise à jour a introduit. 

### Autre

Si vous êtes intéressé par le sujet, prévenez-moi à l'avance svp car je suis long pour écrire des présentations !

### Twitter

https://twitter.com/raphaelbadia

### Email

raphael@badia.cc

**Comment by bloodyowl** [comment]
hello @raphaelbadia, tu serais dispo pour donner ce talk à l'édition du 25 octobre ?

**Comment by raphaelbadia** [comment]
Salut @bloodyowl, non désolé le délai est beaucoup trop court pour moi 😅

**Comment by bloodyowl** [comment]
ce serait bon pour celle du 28 novembre ?

**Comment by raphaelbadia** [comment]
Yes !

**Comment by raphaelbadia** [comment]
@bloodyowl Je viens de voir avec surprise le planning du 29 novembre, du coup ce talk ne vous intéresse plus ou c'est pour une prochaine fois ? 😧 

Je ne serai pas dispo pour celle de décembre, le 31 janvier c'est ok

**Comment by bloodyowl** [comment]
@raphaelbadia my bad, je me suis emmêlé les pinceaux. je te programme pour le 29 novembre !
