### ISSUE TITLE
Good practices

### ISSUE THREAD

**Issue by bloodyowl** [parisjs/talks#19]
## Good practices

*Talk format :* Long

*Description :*

> Un passage en revue des "bonnes pratiques", ces règles établies qu'on ne questionne plus trop. 
Separation of concerns, DRY, TDD, REST, type systems, est-ce que toutes ces pratiques sont encore valables?

*Slides :* 
*Projet :* 
*Twitter :* @bloodyowl

**Comment by PierrickP** [comment]
Hello @bloodyowl Es-que tu es dispo pour faire ce juste au prochain Paris.js, le **mercredi 27 février** (https://www.meetup.com/fr-FR/Paris-js/events/257184550/) ?
Merci

**Comment by bloodyowl** [comment]
@pierrickp yes

**Comment by PierrickP** [comment]
@bloodyowl je veux bien le lien vers les slides. Merci !
