### ISSUE TITLE
L'asynchrone en JS sans le cringe

### ISSUE THREAD

**Issue by tdd** [parisjs/talks#190]
### Format

Long (20 minutes)

### Description

Toi aussi, avoue-le : ton code fait n'importe quoi avec les promesses. Du mélange des genres entre async/await et des chaînes de .then(), des return await qui n'ont pas lieu d'être, des fonctions async sans await, des map() sur du async qui ne font pas ce que tu crois, un manque flagrant de parallélisation quand ce serait pourtant bien utile, une méconnaissance de for await, et j'en passe.

Les promesses et async/await, c'est un peu comme jQuery, PHP, et puis JS en général : tout le monde en fait sans l'avoir vraiment appris sérieusement, et ça donne souvent un sacré foutoir.

Mais plus maintenant. Parce que dans ce talk, Christophe va te donner le bon modèle mental et toutes les clés pour faire ça au cordeau, concis, propre, performant et tout.

### Lien vers vos slides

https://deliciousinsights.github.io/async-js-without-cringe/

### Autre

Version allégée du talk que je donne en confs depuis l'automne 2022.

Assez dispo sur les plages suivantes : 17-21 juillet, >= 11 septembre

### Twitter

porteneuve

### Email

christophe@delicious-insights.com

**Comment by bloodyowl** [comment]
hello! tu serais dispo pour donner ce talk à l'édition du 27 septembre ?

**Comment by tdd** [comment]
Coucou @bloodyowl oui c'est possible ! Rappelle-moi les horaires ?

**Comment by bloodyowl** [comment]
hey! super 😊

ça commence à 19h

**Comment by tdd** [comment]
Parfait !

**Comment by tdd** [comment]
Fais-moi signe quand c'est annoncé, des fois que je vois pas ça passer dans mon fouillis, que je fasse relais etc.

**Comment by bloodyowl** [comment]
@tdd c'est annoncé: https://twitter.com/parisjs/status/1701141160054477251

**Comment by tdd** [comment]
@bloodyowl oui j'ai vu ! Relayé sur mon LinkedIn, Twitter et Masto.
