### ISSUE TITLE
Effect : une solution efficace aux problèmes de software engineering

### ISSUE THREAD

**Issue by antoine-coulon** [parisjs/talks#195]
### Format

Long (20 minutes)

### Description

[Effect](https://www.effect.website/) est une boîte à outils TypeScript qui permet de répondre aux problèmes les plus communs que l’on rencontre lors du développement d’applications, tels que la résilience, la composabilité, la gestion de la concurrence et la maintenabilité du code.

Dans ce talk je présenterai ces problèmes et je montrerai comment Effect les résout de manière efficace avec des exemples.    

### Twitter

https://twitter.com/c9antoine

**Comment by bloodyowl** [comment]
hello @antoine-coulon,

tu serais dispo pour donner ce talk à l'édition du 24 avril ?

**Comment by antoine-coulon** [comment]
Hello @bloodyowl, oui je suis dispo !

**Comment by antoine-coulon** [comment]
Salut @bloodyowl, est-ce que le créneau est confirmé du coup pour l'édition du 24 avril ? Merci

**Comment by bloodyowl** [comment]
hello @antoine-coulon, yes c'est confirmé ! désolé j'avais raté la notif
