### ISSUE TITLE
Arrêtez d'embaucher des seniors, faites devenir vos juniors plus forts qu'eux !

### ISSUE THREAD

**Issue by AlixBou** [parisjs/talks#198]
### Format

Long (20 minutes)

### Description

Quand on veut **améliorer la célérité de son équipe**, on se dit souvent quand l'on doit embaucher des gens plus seniors. Et puis on se retrouve avec une équipe qui ne va pas nécessairement plus vite parce que ses membres n'arrivent pas à s'aligner sur comment réaliser le projet.

Et si la clef ne se trouvait pas là ? Inspirons-nous un peu de Toyota !

Comment ont-ils réussi à créer des voitures de bonnes qualités en n'embauchant pas les meilleurs, mais juste des gens avec l'envie d'apprendre ?

Leur réponse est de **standardiser le travail, apprendre des problèmes et mettre la formation au cœur du système.**

Merci le **lean**, mais concrètement comment on fait ? Je vous propose de vous montrer ce que ça donne sur un projet dans la tech !

### Email

alixb@bam.tech

**Comment by bloodyowl** [comment]
hello @AlixBou, tu serais dispo pour donner ce talk à l'édition du 27 septembre ?

**Comment by AlixBou** [comment]
Hello, 

Oui, je suis dispo pour le 27 !
