### ISSUE TITLE
Deux fans de React amenés à faire de l’Angular et ce qu’ils en ont appris

### ISSUE THREAD

**Issue by JeremD** [parisjs/talks#20]
## Deux fans de React amenés à faire de l’Angular et ce qu’ils en ont appris

*Talk format :* Long

*Description :*

> Après avoir travaillé avec React pendant plusieurs années, la providence nous a rassemblé sur le même projet Angular 4 pendant lequel nous avons pu découvrir ses joies et ses peines.

> Venez si vous êtes intéressés de découvrir la vie au jour le jour de développeurs React forcés par le destin de travailler avec Angular.
> Venez si vous voulez savoir en quoi ça n’était pas si mal.

> Enfin, vous aurez la chance d’apprendre la réponse à la grande question : Quel framework dois-je choisir pour ma prochaine application front, le tout basé sur un retour d'expérience.

*Slides :* https://slides.com/jeremydardour/deck-5-6#/
*Projet :* undefined
*Twitter :* @jeremy_dardour

**Comment by revolunet** [comment]
ca peut être drôle

**Comment by revolunet** [comment]
@JeremD @Loic-carbonne 
un autre event qui pourrait vous intéresser :


<img width="428" alt="capture d ecran 2018-06-09 a 11 05 17" src="https://user-images.githubusercontent.com/124937/41189904-358ba9ba-6bd5-11e8-851f-4c2a3e0bd801.png">

**Comment by PierrickP** [comment]
@JeremD tu confirme ta présence le 27 juin ?
