### ISSUE TITLE
A survival guide to open source

### ISSUE THREAD

**Issue by alexfauquette** [parisjs/talks#202]
### Format

Long (20 minutes)

### Description

Tu t'es déjà demandé qui sont ces personnes qui discutent dans les issues GitHub? Tu voudrais participer à l'amélioration de tes librairies JS préférées?

Ca tombe bien, j'ai quelques conseils et annecdotes à ce sujet

- Pourquoi je trouve toujours ma réponse dans une issue github?
- Ca vaut le coup d'écrire une issue?
- Comment obtenir une réponse à 99%?
- Ecrire une PR, est-ce une bonne idée?

**Comment by bloodyowl** [comment]
hello @alexfauquette! désolé c'est un peu dernière minute mais tu serais disponible pour donner ce talk à l'édition du 25 octobre ?

**Comment by alexfauquette** [comment]
Yes, c'est faisable
