### ISSUE TITLE
GPT4 à l'assaut des test d'intégration API

### ISSUE THREAD

**Issue by Aschen** [parisjs/talks#207]
### Format

Long (20 minutes)

### Description

Les LLMs sont déjà capable de prouesses en génération de code, notamment avec Github Copilot et la génération de tests unitaires.

Par contre, si on parle de tests plus complexes comme un test d'intégration API, les capacités de GPT4 seules sont insuffisantes.

C'est la qu'intervient la panoplie des techniques du développeur GenAI: Prompt Engineering, Chain of Thought, Agent LLM.

Dans ce talk, nous explorerons ensemble les techniques de GenAI nécessaires pour augmenter les capacités de GPT4 afin de générer du code fonctionnel.

Nous verrons également que le développeur Node.js n'est pas en reste avec notamment un gros travail sur le parcours de l'AST pour récupérer une callstack.

### Autre

Si je peux avoir plutôt 30 min c'est vraiment cool car j'aurais l'occasion de développer un peu plus les techniques de GenAI :-)

### Twitter

https://twitter.com/aschen93

**Comment by Aschen** [comment]
PS:

j'ai déjà donné quelques talks:

2018 - Meetup Open Source Talk - Montpellier - Développer rapidement et intuitivement avec Ruby On Rails 
2018 - Paris Open Source Summit - FR - Paris - Et si on créait une app là, tout de suite, sans coder le backend ?
2019 - Open Tech Summit Vietnam - Ho Chi Minh City - Sensors, networks, client apps how to federate components into a IoT apps with Kuzzle IoT?
2020 - Meetup Montpellier JS - Montpellier - Comment écrire du JavaScript performant et optimisable en 2020 ? 
2020 - Node.js Global Summit - Remote/Vietnam - Understand Javascript engines
2022 - Sunnytech - Montpellier - Comprendre le fonctionnement d'un moteur Javascript
2023 - Tech.Rocks - Montpellier - Comment créer un Agent LLM en Node.js

**Comment by bloodyowl** [comment]
hello @Aschen,

tu serais dispo pour donner ce talk à l'édition du 24 avril ?

**Comment by Aschen** [comment]
Hello @bloodyowl !

Oui avec plaisir ;-)

**Comment by Aschen** [comment]
@bloodyowl c'est toujours d'actualité? (Je n'ai pas vu l'évènement Meetup)

**Comment by bloodyowl** [comment]
hello @Aschen, yes!
