### ISSUE TITLE
Faciliter analyse de bugs et logging avec les contextes asynchrones

### ISSUE THREAD

**Issue by gpichot** [parisjs/talks#209]
### Format

Long (20 minutes)

### Description

Les logs prennent une place importante lorsqu'un accès à un environnement de production est limité ou lorsqu'un bug est difficilement reproduisible. Mettre en place des logs est une tâche assez simple en soi, mais elle devient plus complexe lorsqu'on cherche à tracer une suite de logs ou d'appels à travers plusieurs couches.
Ce talk présente un moyen simple pour pouvoir tracer un utilisateur, un traceparent ou une ressource à travers des logs assez simplement avec l'API AsyncLocalStorage.

Topics : logging, AsyncLocalStorage, Async Hooks, cls-hooked

### Lien vers vos slides

[Slides](https://talks-smoky.vercel.app/rca-and-asynclocalstorage?slideIndex=0&stepIndex=0)

### Autre

Talks/Workshops : https://github.com/gpichot/talks

### Email

gabriel@craftvalue.io

**Comment by gpichot** [comment]
Hello,

J'ai rajouté les slides en question. Talk réalisé à l'Accelerator Engineering cette semaine.

**Comment by bloodyowl** [comment]
@gpichot dispo pour l'édition du 24 avril ?

**Comment by gpichot** [comment]
@bloodyowl Yes dispo!
