### ISSUE TITLE
Partager un état entre des windows sans serveur ! 

### ISSUE THREAD

**Issue by achrafl0** [parisjs/talks#212]
### Format

Long (20 minutes)

### Description

Y'a plein de manière différentes pour partager un état à plusieurs fenetres (que ça soit avec un serveur ou non) 

Et en pretextant faire une appli marrante, on pourra voir plusieures apis sympa du web qui sont pas très connues (les SharedWorkers, les BroadcastChannels pour ne pas les citer) 

Du live coding, des anecdotes, bref, tout pour faire plaisir 

![https___dev-to-uploads s3 amazonaws com_uploads_articles_8skuyne3l6gum3eud20z](https://github.com/parisjs/talks/assets/63306573/28646671-ccdd-4459-a650-d0f0065ba21d)

(C'est pas des slides, c'est mon article que j'adapterais pour un format talk) 

### Lien vers vos slides

https://dev.to/notachraf/sharing-a-state-between-windows-without-a-serve-23an

**Comment by bloodyowl** [comment]
hello @achrafl0!

tu serais disponible pour donner ce talk à l'édition du 28 février ?

bonne journée

**Comment by achrafl0** [comment]
> hello @achrafl0!
> 
> tu serais disponible pour donner ce talk à l'édition du 28 février ?
> 
> bonne journée

Hello @bloodyowl, yes totalement
