### ISSUE TITLE
[Tooling] Ecrire du code qui écrit du code,. Quand folie rime avec géni?

### ISSUE THREAD

**Issue by alexfauquette** [parisjs/talks#215]
### Format

Long (20 minutes)

### Description

Chez MUI il y a des scripts magique, qui générent les Proptypes, mettent à jour les pages de documentation, et font les migrations de versions.

Magique jusqu'au jour ù il faut les modifier 😁
Je vous propose de fair un tour des ces scripts et des technologies associés.

Peut être crérer vous votre propre scripts à la fin

**Comment by bloodyowl** [comment]
hello @alexfauquette, tu serais dispo pour donner ce talk à l'édition du 27 mars ?

**Comment by alexfauquette** [comment]
Oui :+1:
