### ISSUE TITLE
Stack Wars : déployer son application en vitesse lumière grâce à Supabase, Zenstack et Vercel

### ISSUE THREAD

**Issue by ThomE2** [parisjs/talks#216]
### Format

Long (20 minutes)

### Description

Lorsqu’un lance un nouveau projet (professionnel ou personnel), le choix des technologies et de l’infrastucture peut être déterminant  pour son succès. Cette stack technique influe directement sur la facilité du déploiement du projet, et la vitesse à laquelle on peut passer de l’idée à l’application.

Laisser moi vous présenter une stack complète grâce à laquelle j’ai pu mettre mon projet en production en seulement 30 minutes.

Pendant ce talk, je montrerai comment :

- Mettre en place une base de donnée avec Supabase
- Traiter la donnée avec Prisma/Zenstack
- Créer une application Next
- Déployer son application sur Vercel

Pour illustrer le sujet, nous mettrons ensemble en production une application complète.

À la fin du talk, vous saurez quels outils utiliser pour déployer votre architecture à la vitesse de l’éclair !

### Email

thomase@theodo.fr

**Comment by jiashengguo** [comment]
Really a great topic! Is your project public avaliable?
