### ISSUE TITLE
Yarn: Hier, Aujourd'hui, et Demain

### ISSUE THREAD

**Issue by arcanis** [parisjs/talks#22]
## Yarn: Hier, Aujourd'hui, et Demain

*Talk format :* Long

*Description :*

> Cela fait maintenant deux ans que Yarn fait parti du paysage Javascript, et s'est installé dans les deux principaux gestionnaires de paquets avec npm.

> Porté par un core maintainer de Yarn, ce talk a pour but de faire une retrospective sur cette période, revenir sur les principales fonctionnalités qui restent son apanage, et offrir un aperçu des avancées à venir.

*Slides :* 
*Projet :* https://yarnpkg.com
*Twitter :* @arcanis

**Comment by arcanis** [comment]
A noter que ce serait idéalement pour le ParisJS de Juillet 🙂

**Comment by PierrickP** [comment]
ahah le forceur, tu t'impose un peu ? :) 
J'imagine, que tu es seulement de passage à ce moment ?

**Comment by arcanis** [comment]
Yes, c'est plus facile pour moi de faire un passage en France à ce moment!

Après comme j'ai dit c'est "idéalement", et c'est plus dans le sens "just
in case, ne me faites pas passer dans la phase de sélection de juin"
qu'autre chose. M'imposer n'est pas le but :)

**Comment by PierrickP** [comment]
ahah t'inquiete c'etait pour rigoler :)
Par contre, je viens de tilter que juillet, il y a pas. Juin, Aout, septembre ...

**Comment by arcanis** [comment]
Superlipozut 🙁 

Bon, eh bien n'importe quel mois à partir d'Août, tant pis :p

**Comment by PierrickP** [comment]
Peux-tu me confirmer ta présence pour le 29 aout ?

**Comment by arcanis** [comment]
Hey @PierrickP - je pense que ça va être chaud pour août 🙁 Possible de le décaler?

**Comment by PierrickP** [comment]
Carrement, 26 septembre ?

**Comment by arcanis** [comment]
💯 💯 💯

**Comment by PierrickP** [comment]
Coucou

Paris.js est partenaire de http://bestofweb.paris (et je suis dans l'orga).
Pour rappel, c'est une conférence d'un jour à Paris, organisée par des bénévoles.
Le programme est un mix des meilleurs sujets des meetups Parisiens et d'un CFP.

Nous avons sélectionné ton talk en bestof de Paris.js ✨ !

Pour être hyper exact, on a pas sélectionné ce sujet mais un sujet que tu pourrais faire sur Yarn.
Es-que ça t’intéresse toujours ? :) Et es-que tu es dispo et chaud pour faire un talk ce 7 Juin 2019 ?

Hésite pas si tu as la moindre question, ici ou par mail hello@pierrickp.xyz
Merci

**Comment by arcanis** [comment]
Oh c'est trop cool ! J'aurais été ravi, mais malheureusement je suis déjà sur les bancs pour faire un talk le même jour à Web2Day 😢
