### ISSUE TITLE
Code Prettier Code

### ISSUE THREAD

**Issue by teogeos** [parisjs/talks#23]
## Code Prettier Code

*Talk format :* Long

*Description :*

> L'objectif de ce talk est de montrer comment et pourquoi convaincre une équipe d'ajouter Prettier à ses projets js/ts dans le court terme. J'y démontre la valeur ajoutée de Prettier, et comment l'installer de bout en bout: comment l'ajouter au projet, l'intégrer aux linters existants, organiser la PR qui appliquera Prettier, merger facilement les branches des autres membres de l'équipe, et les meilleurs moyens de faire en sorte d'appliquer Prettier sur tous les changements futurs.

> L'objectif est vraiment de montrer à qui serait intéressé par Prettier, que la complexité de son ajout dans un projet, même gros, est assez réduite pour considérer de le faire sans trop attendre, et que sa valeur ajoutée en vaut le prix.

*Slides :* https://docs.google.com/presentation/d/1Y7QM9teTVlzu9QhcbNYTTaPBkhUbeQOed0d25fo5cL8/edit?usp=sharing
*Projet :* https://github.com/teogeos/prettier-demo
*Twitter :*

**Comment by Freddy03h** [comment]
Hello @teogeos, tu es dispo pour faire ce talk au meetup ParisJS#78 du mercredi 24 octobre ? Merci.

**Comment by Freddy03h** [comment]
ping @teogeos ?

**Comment by teogeos** [comment]
Je ne vais pas pouvoir désolé. Il se trouve que je le présente ailleurs le même jour justement. Mais au prochain ParisJs avec plaisir si ça vous intéresse.

**Comment by Freddy03h** [comment]
Ok pas de soucis !
J’ai juste une petite question sur la longueur du talk, est ce que c’est bien un long talk (20min) ou plutôt un court (5min) ? Vu que je vois qu’une dizaine de slides.
Merci !

**Comment by Freddy03h** [comment]
D'accord !

**Comment by PierrickP** [comment]
Hello @teogeos es-que tu peux le présenter se mois-ci 28 novembre ?

**Comment by teogeos** [comment]
A priori oui, ce serait quel jour ?

**Comment by PierrickP** [comment]
Le *30 janvier*

**Comment by teogeos** [comment]
Ok pour le 30 ça me va

**Comment by PierrickP** [comment]
@teogeos Es-que le lien de ta présentation est ok. nous aurions besoin de la télécharger en local pour tout mettre sur une seule machine
Es-que tu auras besoin absolument d'internet ?

**Comment by PierrickP** [comment]
Es-que tu peux rejoindre le meetup de Paris.js, j'aimerai t'ajouter en animateur

**Comment by teogeos** [comment]
Hello @PierrickP 
Le lien est ok oui
Mais c'est quand même mieux si je peux utiliser ma machine. Je fais une démo sur du code sur mon IDE.

Il me faut internet aussi si possible oui, mais à priori je peux utiliser ma 4G

**Comment by teogeos** [comment]
A priori je suis déjà membre du groupe parisjs. Je me suis ajouté à la waitlist du meetup de ce soir

**Comment by Freddy03h** [comment]
C'est bon je viens de te passer en liste principale et animateur sur meetup
