### ISSUE TITLE
Delivering Fast and Beautiful Images and Video

### ISSUE THREAD

**Issue by dougsillars** [parisjs/talks#24]
## Delivering Fast and Beautiful Images and Video

*Talk format :* Long

*Description :*

> The average website page weight is 50% images and 25% video. As the images and videos delivered to mobile devices get larger and larger, the load time of websites gets slower and slower. Further complicating matters, there are thousands of screens and devices with varying resolutions and CPU power that receive this content. In this talk, we’ll examine strategies to send the perfect image or video to every device, ensuring a fast, beautiful rendering of your content. We’ll look at how to test our content, and describe responsive images, delivering progressive images, and finally optimizing all of this content for fast delivery to each screen. Attendees will walk away with a better understanding of how to efficiently deliver beautiful images to every device that accesses their content.

*Slides :* https://www.slideshare.net/dougsillars/
*Projet :* 
*Twitter :* @dougsillars

**Comment by PierrickP** [comment]
pre-planned for 8/29

**Comment by dougsillars** [comment]
I'm planning my trip!  Looking forward to it!

**Comment by PierrickP** [comment]
If it's still good for you, we selected your talk for the 29th.
I ll add you on the meetup event

**Comment by dougsillars** [comment]
Perfect. Thanks

**Comment by PierrickP** [comment]
@dougsillars did you joined Paris.js meetup group ?

**Comment by dougsillars** [comment]
Done :)
