### ISSUE TITLE
From Heroku / Github / CircleCI to Kubernetes (helm/vault) / Gitlab CI CD 

### ISSUE THREAD

**Issue by JWimsingues** [parisjs/talks#25]
## From Heroku / Github / CircleCI to Kubernetes (helm/vault) / Gitlab CI CD 

*Talk format :* Long

*Description :*

> Rex sur la migration d'une société de Heroku (app engine GCP like), Github et CircleCI en Saas vers Kubernetes (via Helm et Vault), et gitlab (avec gitlab-ci) pour la CI/CD. 

*Slides :* https://docs.google.com/presentation/d/1Sy-4T-Nj4tyj07FeQhUIFNsFOtu9vlWnXXQt4RKVHSY/edit?usp=sharing
*Projet :* Migration de GitHub / Circle / Heroku vers Gitlab / Gitlab-ci / Kubernetes (Helm + Vault)  
*Twitter :* @JWimsingues (https://twitter.com/jwimsingues)

**Comment by PierrickP** [comment]
@JWimsingues coucou, tu pourrais éditer la description et mettre un lien vers les slides.
J'aimerai comparer avec #25 voir si c'est complémentaire ou a cheval .
Ça serait top si on peut faire une édition spécial k8s

**Comment by JWimsingues** [comment]
Salut @PierrickP je ne peux pas mettre les slides ca va spoil le meetup CNCF que je tiens mardi prochain. Je mettrai les slides quand j'aurai fait la prez' si ca ne te dérange pas. Sinon vs #29 c'est exactement la même chose à part qu'il semble avoir eu plus de difficulté si j'en crois l'abstract.

**Comment by PierrickP** [comment]
@JWimsingues il vient de mettre les slides, tu peux regarder ?
Sinon, tu peux faire un sujet avancé sur Kubernetes qui irait approfondir son sujet ?

J'essaye juste de voir si on peux mixer les 2, sinon on fera sur 2 mois

**Comment by JWimsingues** [comment]
Je pense que ce sera très complémentaire en faite, je mets à jour les slides, dis moi ce que tu en penses. On peut aussi lui demander. Pour info comme dis dans le commentaire précédent je fais ce talk chez CNCF Dailymotion demain je pourrai te donner les feedbacks du coup.

**Comment by PierrickP** [comment]
@JWimsingues ok tu me dis. Je pense qu'on tiens un excellent theme !

**Comment by PierrickP** [comment]
@JWimsingues tu peux me confirmer ta présence pour le 27 mars ?
Je vais faire l'evenement meetup

**Comment by JWimsingues** [comment]
Je ne sais pas si ça intéressera beaucoup de gens au final dans un meetup js, c'est vraiment plus de l'infra / cloud / devops. A voir si tu veux vraiment me faire passer, je pense que tu devrai peut être en discuter avec les autres responsables ! Mais sinon oui je suis dispo le 27 mars !

**Comment by PierrickP** [comment]
@JWimsingues oui oui oui t'inquiete pas :)
tu auras du public !

**Comment by PierrickP** [comment]
Peux-tu rejoindre le groupe meetup de parisjs pour que je t'ajoute en temps qu'animateur ?
