### ISSUE TITLE
The Amazing Tale of the Web S01E03 - The Rise of JS

### ISSUE THREAD

**Issue by loicortola** [parisjs/talks#26]
## The Amazing Tale of the Web S01E03 - The Rise of JS

*Talk format :* Long 

*Description :*
Le dernier de la trilogie, the Rise of JS couvrira les 10 dernières années.
Les beaux jours du web dynamique battent leur plein, et déjà quelques transitions arrivent.
Le Wap prend sa retraite, les netbooks et Smartphones arrivent : une transformation doit s'opérer.
Un jour, Google annonce son navigateur Chrome, cachant un moteur qui va changer la donne. #DynamicWeb #W3C #HTML5 #WebFrameworks #V8

Cet épisode 3, c'est comprendre la transition du monde dynamique vers un modèle client-serveur, la fracture engendrée par les nouveaux devices, le mouvement des technologies pour répondre à ces nouveaux usages (Node.js, Play, etc...) et bien sur les frameworks JS

*Twitter :* https://twitter.com/loicortola

**Comment by PierrickP** [comment]
😂 on te réserve jusqu’à la fin d'année ?
Plus sérieusement, la prochaine date c'est **29 août**

**Comment by loicortola** [comment]
Hahaha :D
c'est long l'histoire du web... Promis c'est le dernier celui là, après j'arrête de vous embêter ;)

**Comment by PierrickP** [comment]
@loicortola Tu confirme pour le 29 ?
