### ISSUE TITLE
Front-end architecture in practice

### ISSUE THREAD

**Issue by wittydeveloper** [parisjs/talks#27]
## Front-end architecture in practice

*Talk format :* Long

*Description :*

> Le terme d'architecture est désormais plus que pertinent coté front-end.
> Après une courte introduction sur les 3 révolutions du web, nous verrons comment appliquer simplement des notions d'architecture pour mettre en place une roadmap et une guideline sur votre projet.

*Slides :* https://slides.com/charlypoly-1/deck-9
*Projet :* 
*Twitter :* @whereischarly

**Comment by olachgar** [comment]
Yes

**Comment by wittydeveloper** [comment]
Hello @PierrickP 

Est ce que vous avez des news sur la sélection des talks ?
Quels sont les critères de sélection ?

**Comment by PierrickP** [comment]
@wittydeveloper la prochaine sélection devrait etre jeudi 13 septembre.
On vient de reprendre les Paris.js, on va pouvoir commencer à dépiler notre looongue liste de sujets.
Cependant, le tiens est assez vieux, on devrait pouvoir le faire passer en septembre ou octobre.
Hésite pas a suivre la mailing-list https://groups.google.com/forum/#!forum/parisjs et de venir defendre ;) ton sujet a la reunion

**Comment by PierrickP** [comment]
Hello @wittydeveloper Es-que tu es dispo pour faire ce sujet au prochain Paris.js, le **mercredi 27 février** (https://www.meetup.com/fr-FR/Paris-js/events/257184550/) ?
Merci

**Comment by wittydeveloper** [comment]
Yes ! 👍
