### ISSUE TITLE
The Challenging Migration from Heroku to Google Kubernetes Engine (🇬🇧/🇫🇷)

### ISSUE THREAD

**Issue by adrienjoly** [parisjs/talks#29]
## The Challenging Migration from Heroku to Google Kubernetes Engine (🇬🇧/🇫🇷)

(ancien titre: How to migrate from Heroku to Google Kubernetes Engine)

*Talk format :* Long (20 mn)

*Description :*

> L'été dernier, on a migré une application Node.js distribuée, de Heroku vers Google Kubernetes Engine. Je pensais que ça allait être facile. Hé bien j'avais tort ! 😅
> Je vais vous raconter les ratés les plus épiques auxquels j'ai du faire face pendant cette migration. Et si vous êtes sympas, je vous expliquerai les astuces que j'ai appliquées pour corriger le tir !

Keywords: Deployment, Docker, Scalability, K8S, GCP

*Slides :* https://docs.google.com/presentation/d/1DrWXcp_NMGJtLm4EcXbeUnkQb8l384ukH4bc9tSK_fc/edit (presenté à Node.js Paris le 18 Octobre 2018)
*Projet :* Algolia Crawler
*Twitter :* @adrienjoly

Note: The talk can be given in French or English. Slides are in English.

**Comment by PierrickP** [comment]
@adrienjoly coucou, tu pourrais editer la description et mettre un lien vers les slides.
J'aimerai comparer avec #25 voir si c'est complémentaire ou a cheval .
Ca serait top si on peut faire une edition spécial k8s

**Comment by adrienjoly** [comment]
Désolé pour le temps de réaction. Je fais ça tout de suite !

**Comment by adrienjoly** [comment]
Done !

Par rapport à #25, le scope est plus fin (je ne parle pas de CI par exemple), il y a moyen que le ton soit plus léger. Même si je montre des exemples de code, le but de cette prez est plus de montrer les gàleres imprévues et la complexité de K8S par rapport à Heroku en en rigolant plutot que de faire un comparatif fonctionnel ou un tuto.

Pour info: le talk avait été super bien reçu par le public de Node.js Paris, et je vais très prochainement publier ce récit sous forme d'article sur le blog d'Algolia.

**Comment by adrienjoly** [comment]
Pour info, on a publié le blog post correspondant hier: https://blog.algolia.com/challenging-migration-heroku-google-kubernetes-engine/

**Comment by PierrickP** [comment]
@adrienjoly tu peux me confirmer ta présence pour le 27 mars ?
Je vais faire l'evenement meetup

**Comment by adrienjoly** [comment]
@PierrickP Yes, ça me va ! À bientôt, donc ! :-)

**Comment by adrienjoly** [comment]
Voici les slides du talk que j'ai donné mercredi: https://docs.google.com/presentation/d/1eVk1Px99bk-5BGKYL3MjZuQQqRezHVwtPiGFynBtsyE/edit?usp=sharing

Et la version article (en anglais): https://blog.algolia.com/challenging-migration-heroku-google-kubernetes-engine/
