### ISSUE TITLE
Angular, un framework au service de l’expérience utilisateur

### ISSUE THREAD

**Issue by AABDI75** [parisjs/talks#3]
## Angular, un framework au service de l’expérience utilisateur

*Talk format :* Long

*Description :*

> Après avoir fait état de ce qu’attend un utilisateur d’une application web en terme de rapidité, d’ergonomie et d’accessibilité, nous verrons comment Angular, Material et la mise en place d’une architecture structurée permet de répondre à ces problématiques. Cette présentation n’a volontairement pas vocation à rentrer dans des détails techniques mais plutôt de donner un aperçu de l’étendu des possibilités de ce framework ainsi que des ressources pour aller plus loin.

*Slides :* undefined
*Projet :* undefined
*Twitter :* undefined

**Comment by PierrickP** [comment]
📔 Eu par téléphone, ca serait pour faire avec #4 en avril ou mai avec Abbeal / Numa

Par contre il nous faudrait le github de l'auteur.
