### ISSUE TITLE
How to refactor your GraphQL API without bugs using Relay and static typing

### ISSUE THREAD

**Issue by bastoche** [parisjs/talks#30]
## How to refactor your GraphQL API without bugs using Relay and static typing

*Talk format :* Short

*Description :*

> Is this field still used ? Can I safely delete it ? When refactoring an API, that's a question you can ask yourself. In this talk, I will show how Relay and static typing can help you refactor your GraphQL API quickly and without introducing defects.

*Slides :* TBD
*Projet :* N/A
*Twitter :* https://twitter.com/bast0che

**Comment by Freddy03h** [comment]
Bonjour @bastoche ! Est ce que tu es disponible pour faire ton talk au meetup ParisJS#78 du mercredi 24 octobre ? Il reste un slot pour un lightning talk !

**Comment by bastoche** [comment]
Hello, je n'ai pas vu la notification, désolé ! Je reste disponible pour faire ce talk :)

**Comment by PierrickP** [comment]
Hello,
Nous avons séléctionné ce sujet pour le prochain Paris.js, le **mercredi 24 avril** chez Daveo (https://www.meetup.com/fr-FR/Paris-js/events/260336485/)
Peux-tu me confirmer ta présence en temps que speaker ?

Merci !

**Comment by Freddy03h** [comment]
Up @bastoche ?

**Comment by bastoche** [comment]
Arf, comme je ne reçois pas d'email pour les notifications github, j'ai encore loupé le coche :(

Je viens de les réactiver, pour que ça n'arrive pas une 3ème fois, mais n'hésitez pas à me contacter directement par email si je ne suis pas réactif !

J'en ai profité pour élargir le scope: j'ai testé avec Flow et Typescript, ça marche avec les deux.

**Comment by PierrickP** [comment]
@bastoche on fait un dernier essai, es-tu dispo pour le *29 mai 2019* ? https://www.meetup.com/fr-FR/Paris-js/events/260336623/

**Comment by bastoche** [comment]
Cette fois j'ai reçu l'email !
Malheureusement c'est la veille de l'ascension et j'ai prévu de partir en week-end 😢

**Comment by PierrickP** [comment]
Pas de souci, alors ca sera peut-etre pour la rentrée :D

**Comment by Freddy03h** [comment]
@bastoche Hello ! Est ce que tu es dispo le 30 octobre ? Merci :)

**Comment by bastoche** [comment]
Hello @Freddy03h, oui je suis disponible !

**Comment by Freddy03h** [comment]
Je te confirme du coup pour le 30 octobre !!

**Comment by Freddy03h** [comment]
Je vois que c'est un talk short, tu me confirme que c'est bien un lightning talk de 5 min que tu prévois de faire ?

**Comment by bastoche** [comment]
Je peux adapter le contenu, ça tiendra en 5 min.

**Comment by Freddy03h** [comment]
Hello ! Pour info un speaker n'a pas confirmé sa présence, alors tu peux prendre 20min pour ton talk si tu veux !

**Comment by bastoche** [comment]
Ok, je garantis pas de remplir les 20 minutes, mais je prends. À demain !

**Comment by Freddy03h** [comment]
> Ok, je garantis pas de remplir les 20 minutes

Pas de soucis ! À demain ^^

**Comment by bastoche** [comment]
@Freddy03h Pour les slides il faut que je vous les fournisse à l'avance? Ou bien je viens juste avec mon laptop?

**Comment by PierrickP** [comment]
@bastoche vient avec ton laptop. En général chaque speaker utilise son matos
