### ISSUE TITLE
You’re not doing REST (but it’s fine)

### ISSUE THREAD

**Issue by Haroenv** [parisjs/talks#31]
## You’re not doing REST (but it’s fine)

*Talk format :* Long

*Description :*

It’s coming up quite a bit now: “REST is dead, use GraphQL”. And you might feel guilty for not having the time to learn it yet. But what do they really mean with “REST is dead”? Look at your devtools on any website, count how many requests are being done, aren’t all of those REST? The truth is most aren’t, but it’s okay, don’t panic. It’s not necessary to do real REST nor is it necessary to do GraphQL to make a useful site. 

*Slides :* not yet made
*Projet :* 🤷‍♀️
*Twitter :* https://twitter.com/haroenv

**Comment by revolunet** [comment]
Yes please ;)

**Comment by clementgalidie** [comment]
👍

**Comment by PierrickP** [comment]
@Haroenv coucou, on fait un peu de nettoyage dans la liste. Est-ce que c'est un sujet que tu souhaites toujours présenter ?
Sinon tu peux close ;)
Merci

**Comment by Haroenv** [comment]
Oui, je pourrai ca faire

**Comment by mauricesvay** [comment]
Hello @Haroenv  !

We are considering starting meetups again, but 100% online with shorter talks (10-15 minutes).

- Is this talk still relevant?
- Could it be done in a shorter amount of time?

**Comment by Haroenv** [comment]
The subject can still be relevant, but I haven't worked on that part of the stack in a while, so I don't think I can give a good talk, I'll think about new subjects!

**Comment by mauricesvay** [comment]
Thanks for updating the gh issue!
