### ISSUE TITLE
Vulcan.js: le "Rails" de GraphQL

### ISSUE THREAD

**Issue by SachaG** [parisjs/talks#32]
## Vulcan.js: le "Rails" de GraphQL

*Talk format :* Long

*Description :*

> Je suis le maintainer principal de Vulcan.js, un nouveau framework full-stack qui a pour mission de simplifier la création d'applis React/GraphQL en proposant des outils tels que la génération automatique du schema et de l'API GraphQL, des formulaires, et des listes données. 

> Je viendrai a Paris pour parler a DotJS donc je pensais que je pourrai peut-etre profiter de l'occasion pour parler également a ParisJS?

> Sacha Greif

*Slides :* 
*Projet :* http://vulcanjs.org
*Twitter :* @sachagreif

**Comment by PierrickP** [comment]
Nous allons faire un meetup spécial dotjs juste avant.
Ça sera en CFP exprès pour l’événement.
J'imagine que tu n'es que de passage en France.
Peut-tu me dire si tu es dispo sur l'une des dates suivantes:

+ [ ] #76 Mercredi 29 aout
+ [ ] #77 Mercredi 26 septembre
+ [ ] #78 Mercredi 24 octobre
+ [ ] #79 Mercredi 7 Novembre (Spécial Dot)
+ [ ] #80 Mercredi 28 Novembre

**Comment by SachaG** [comment]
Oui je pensais justement a l'évenement du 7 Novembre?

**Comment by PierrickP** [comment]
@SachaG ok ca doit pouvoir se faire. 
Es-que ca va pas etre trop doublon par rapport à ton talk à Dot?

**Comment by SachaG** [comment]
Oui voila mon compte: https://www.meetup.com/members/21462091/

Par contre je suis désolé, j'avais mal calculé et en fait le meetup est le meme jour que mon arrivée à Paris… Il faudrait que je vienne directement depuis l'aéroport, et je risque d'etre un peu en retard. Du coup je pensais demander à @Apollinaire, un autre membre de la team Vulcan, de faire la présentation (ou au moins la commencer) à ma place. Est-ce que ça poserait problème? 

Vraiment désolé pour le changement de dernière minute, j'aurai du mieux regarder les dates :(

**Comment by PierrickP** [comment]
Ca me semble pas un gros probleme :)
Je vais mettre @apollinaire ou @SachaG 
Au pire, vous pouvez passer en dernier, ~ 20h30.
Attention, c'est un peu excentré de Paris

**Comment by SachaG** [comment]
Vraiment désolé de pas avoir pu etre là, mon avion est parti avec 3h de retard finalement :( J'espère que tout s'est bien passé quand meme!

**Comment by PierrickP** [comment]
@SachaG T'inquiete pas, @Apollinaire a très bien géré malgré les questions 😹 
Bon talk qui suscite pas mal de curiosité !

**Comment by PierrickP** [comment]
@SachaG @Apollinaire es-que l'un de vous peut me donner un résumé de 2-3 lignes en anglais pour présenter le talk. C'est pour le site.

Merci

**Comment by Apollinaire** [comment]
Vulcan.JS, a fullstack GraphQL + React framework, lets you ship webapps fast, using the latest technologies. In this talk, we see the origin story of the framework and an overview of its main features
- Slides : https://apollinaire.github.io/vulcan-parisjs-slides
- Github : https://github.com/VulcanJS/Vulcan
- Slack: https://slack.vulcanjs.org
