### ISSUE TITLE
Modifier votre codebase à l'aide de codemods

### ISSUE THREAD

**Issue by AugustinLF** [parisjs/talks#34]
## Modifier votre codebase à l'aide de codemods

*Talk format :* Long

*Description :*

> L'idée de changer un composant qui est utilisé dans quatre cent fichiers de votre codebase vous angoisse ? Certains cas sont trop complexes pour des regex (et de toute façon, qui sait écrire une regex ?) Vous n'êtes pas des machines. Ça tombe bien, votre PC l'est ! Lors de cette talk, je vais présenter jscodeshift, un outil en CLI permettant d'écrire des transformations de code en manipulant un AST.

*Slides :* 
*Projet :* https://github.com/facebook/jscodeshift
*Twitter :* @gusguslf

**Comment by PierrickP** [comment]
Hello,
Nous avons séléctionné ce sujet pour le prochain Paris.js, le **mercredi 24 avril** chez Daveo (https://www.meetup.com/fr-FR/Paris-js/events/260336485/)
Peux-tu me confirmer ta présence en temps que speaker ?

Merci !

**Comment by AugustinLF** [comment]
@PierrickP Avec grand plaisir !

**Comment by mauricesvay** [comment]
@AugustinLF est-ce que je peux publier la vidéo de ton talk? https://youtu.be/sWN7b4g_HMg

**Comment by AugustinLF** [comment]
@mauricesvay Avec plaisir !

**Comment by mauricesvay** [comment]
@AugustinLF C'est en ligne, merci !
