### ISSUE TITLE
Chrome dev Tools Tips

### ISSUE THREAD

**Issue by wallet77** [parisjs/talks#35]
## Chrome dev Tools Tips

*Talk format :* Long

*Description :*

> On connait tous chrome dev tools, depuis des années ça nous permet d'inspecter le DOM et de mesurer les temps de réponses.
> Mais cet outils regorge de fonctionnalités parfois un peu cachées.
> Et si on tentait de les déterrer et d'expliquer pourquoi certaines sont juste incroyables.
> Les performances et leur analyse ne sont plus une options mais une nécessité.

*Slides :* 
*Projet :* 
*Twitter :* @Vince_Vallet

**Comment by PierrickP** [comment]
Hello @wallet77 
On aimerait sélectionner ton sujet pour le paris.js de janvier, *Mercredi 29 janvier*.
Peux-tu me confirmer ta présence ?

**Comment by Freddy03h** [comment]
Hello, petit up @wallet77 ?

**Comment by wallet77** [comment]
Salut,

Ca va être un peu court pour moi d'ici fin janvier. Pour février ce serait top mais si jamais vous avez une urgence je peux faire un miracle ;)

**Comment by Freddy03h** [comment]
Merci de ta réponse, alors en fait on essayait de faire un spécial un peu "tooling" sur Janvier vu qu'on a remarqué plusieurs sujets dans ce thème (un peu large certes).
Moi je veux pas te forcer, je crois qu'il y a une autre proposition de talk sur la console un peu similaire qu'on peut utiliser à la place si ce n'est pas possible pour toi.
Après pour être transparent, 2 sujets un peu similaires on va essayer de les espacer dans le temps et pas les faire sur deux mois à la suite pour éviter d'être trop redondant…

**Comment by wallet77** [comment]
Du coup vous avez pu trouver un autre speaker ?
J'ai vérifié de mon côté j'ai bien un début de présentation, faudra que je me replonge assez rapidement dedans si jamais vous sélectionnez ce talk ;)

**Comment by Freddy03h** [comment]
Comme je le disais cela dépend de toi, l'autre talk c'est #76

**Comment by wallet77** [comment]
Allez go je vais bosser dessus d'ici le 29 ;)
