### ISSUE TITLE
Découvrir React Suspense

### ISSUE THREAD

**Issue by topheman** [parisjs/talks#36]
## Découvrir React Suspense

*Talk format :* Long

*Description :*

> "Suspense", c'est une des fonctionnalités parmi d'autres qui arriveront dans les prochaines versions de React.
> Cela pourrait changer la façon dont nous raisonnons pour gérer le chargement asynchrone des données et leur rendu.
> Je vous propose de vous faire découvrir :
>
> - Qu'est ce qu'est "suspense"
> - Comment le tester dès aujourd'hui
> - Ce que cela implique pour le code que vous écrivez actuellement
>
> Cela autour d'un projet sur lequel je travaille.

*Slides :* A faire
*Projet :* https://react-fiber-experiments.surge.sh/
*Twitter :* [@topheman](https://twitter.com/topheman)

**Comment by PierrickP** [comment]
@topheman oups my bad. Merci !

**Comment by topheman** [comment]
Ce talk ne tient pas dans un format 20min. Ce n'est pas faute d'avoir retiré tout ce qui dépassait et optimisé la forme pour perdre le moins de temps en présentation tout en restant un maximum compréhensible sur le fond.

J'ai donné ce talk il y a quelques jours au meetup ReactJS, ça tient en 35min.

**Comment by PierrickP** [comment]
@topheman bah c'est pas bien grave. On passera les questions. Ca arrive d'avoir des sujets en peu plus cours, ca compense.

**Comment by PierrickP** [comment]
On fait un peu de nettoyage dans les trèèèèès vieux sujets.
Du coté organisation c'est compliqué d'avoir un sujet bien plus long que les autres.
Je vais closer. Si tu peux le faire en 20min, hésite pas à refaire une proposition.
Merci !

**Comment by topheman** [comment]
Tu fais bien de le fermer. Le talk parlait de features React en cours de développement l'année dernière (2018), cachées derrière un flag. Depuis, l'api a changé et ils commencent à en ouvrir quelques morceaux.

Ça vaudra le coup que je fasse un talk là-dessus mais remis au goût du jour. J'ouvrirai une nouvelle issue quand j'aurai quelque chose de prêt.
