### ISSUE TITLE
Alexa Skills Kit pour Node.js

### ISSUE THREAD

**Issue by MariaWTB** [parisjs/talks#37]
## Alexa Skills Kit pour Node.js

*Talk format :* Long

*Description :*

> Découvrez l'Alexa Skills Kit pour Node.Js, et apprendre comment construire votre skill Alexa - (une application à commande vocale). On vous aide à passer la cértification, et publier votre skill sur la boutique Amazon Alexa avant le 13 novembre pour faire parti de l'Alexa Skills Challenge.

> - Créez une fonction sur AWS [$100 credits avec le challenge]
> - Configurez le skill utilisant le portail Amazon Developer << Focus du talk
> - Test Skill

> Ce talk sera animé par Benoît Nachawati - Technical Evangelist, Amazon Alexa France, qui accompagne les développeurs à créer des skills engageantes, tout en les guidant dans leur parcours de découverte des interfaces vocales.

*Slides :* 
*Projet :* https://developer.amazon.com/fr/alexa-skills-kit/alexa-skill-quick-start-tutorial-nodejs
*Twitter :* @bnachawati

**Comment by PierrickP** [comment]
bonjour,
Merci pour votre soumission.
Je vois que dans la description, il y a une histoire de date.
Es-que le sujet peut se faire après ?

**Comment by MariaWTB** [comment]
Bonjour! Pour les dates, c'est parce qu'il y a une challenge création Alexa Skills - et il faut publier avant le 30 Oct (la meilleure gagne €3K, mais tlm reçoit un echo dot pour soumettre une skill)... je pense que c'est possible de faire le talk (sans penser au challenge) mais j'attends une réponse et reviens vers vous

**Comment by MariaWTB** [comment]
OUI c'est possible pas de problème :)
