### ISSUE TITLE
Industrialisation des tests end-to-end

### ISSUE THREAD

**Issue by ViBiOh** [parisjs/talks#39]
## Industrialisation des tests end-to-end via Selenium/Nightwatch/Browserstack

*Talk format :* Long

*Description :*

* Pourquoi faire des tests fonctionnels via Selenium ?
* Mise en place et industrialisation des tests *end-to-end* (Docker / Nightwatch / Browserstack)
* Problématiques rencontrées lors de tests multi-browsers.
* Approche pour des tests de non-régressions visuels

*Slides :* https://talks.vibioh.fr/indus_e2e/
*Twitter :* https://twitter.com/MeilleursAgents

**Comment by PierrickP** [comment]
@ViBiOh c'est le sujet prevu pour octobre ?

**Comment by ViBiOh** [comment]
@PierrickP Ce serai plutôt prévu pour Novembre, mois où nous sommes pressentis pour héberger ParisJS. On peut en discuter de vive voix demain

**Comment by PierrickP** [comment]
@ViBiOh ah oui pardon, c'est bien novembre de prevu !
Parfait

**Comment by Freddy03h** [comment]
Yep, pour le ParisJS 80 du 28 novembre.

**Comment by ViBiOh** [comment]
@Freddy03h @PierrickP Afin d'ajuster au mieux mes slides, la durée d'un talk long est de combien ? 30min ?

**Comment by PierrickP** [comment]
@ViBiOh 20 + questions. Tu peux faire 30 sans questions :)

**Comment by ViBiOh** [comment]
Avec les questions c'est mieux, ok pour 20. Merci pour ton retour rapide ;)

**Comment by PierrickP** [comment]
Après, t’inquiète pas on est pas à la minute

**Comment by Freddy03h** [comment]
20 min c'est surtout bien comme format pour ne pas perdre l'attention de l'auditoire, après oui on est pas à la minute mais sinon oui ça empiète sur le temps des questions et c'est dommage.

**Comment by ViBiOh** [comment]
@PierrickP Lien vers mes slides mis à jour https://talks.vibioh.fr/indus_e2e/

Merci pour l'organisation, c'était, comme d'habitude, très sympathique et varié en terme de contenu ;)

**Comment by Freddy03h** [comment]
Merci à vous de l'accueil c'était très cool ! 😁
