### ISSUE TITLE
GraphQL, apollo client ?

### ISSUE THREAD

**Issue by AABDI75** [parisjs/talks#4]
## GraphQL, apollo client ?

*Talk format :* Long

*Description :*

> Introduction à GraphQL, langage de query permettant aux clients d’une API de choisir les données qu’ils reçoivent, et de souscrire aux changements de cette donnée très simplement. Présentation d’Apollo Client, le client
> permettant de consommer une API GraphQL, REST, et même le state local.

*Slides :* undefined
*Projet :* undefined
*Twitter :* undefined

**Comment by PierrickP** [comment]
📔 Eu par téléphone, ca serait pour faire avec #3 en avril ou mai avec Abbeal / Numa

Par contre il nous faudrait le github de l'auteur.
