### ISSUE TITLE
Elm: beginners and production compliant (en français)

### ISSUE THREAD

**Issue by sebsheep** [parisjs/talks#40]
## Elm: beginners and production compliant (en français)

*Talk format :* Long

*Description :*

> Ce talk présente le langage Elm en mettant en valeur:
> * sa simplicité de prise en main pour les débutants,
> * la fiabilité des applications écrites en Elm.

> Live coding included !

> Ce talk n'a pas pour vocation à apprendre le langage, mais plutôt montrer son potentiel.

*Slides :* https://slides.com/sebbes/deck
*Projet :* https://elm-lang.org/
*Twitter :*

**Comment by PierrickP** [comment]
Hello,
Nous avons séléctionné ce sujet pour le prochain Paris.js, le **mercredi 24 avril** chez Daveo (https://www.meetup.com/fr-FR/Paris-js/events/260336485/)
Peux-tu me confirmer ta présence en temps que speaker ?

Merci !

**Comment by sebsheep** [comment]
Salut,

C est ok pour moi!

Sébastien

Le ven. 12 avr. 2019 à 11:05, Pierrick PAUL <notifications@github.com> a
écrit :

**Comment by mauricesvay** [comment]
@sebsheep est-ce que je peux publier la vidéo de ton talk? https://youtu.be/kLumTtZ8awI

**Comment by sebsheep** [comment]
@mauricesvay Pas de soucis, bien sûr. Merci pour la captation! 

Sébastien

**Comment by mauricesvay** [comment]
@sebsheep parfait, c'est en ligne!
