### ISSUE TITLE
Présentation de l'Alexa Skills Challenge (ASK Kit Node.js) en 5 minutes !

### ISSUE THREAD

**Issue by MariaWTB** [parisjs/talks#41]
## Présentation de l'Alexa Skills Challenge (ASK Kit Node.js) en 5 minutes !

*Talk format :* Short

*Description :*

> Découvrez l'Alexa Skills Challenge basé sur l'Alexa Skills Kit sur Node.Js dans 5 minutes :
> - De conseils Voice Design - les 3 différents de commandes vocaux possibles et quelques tips 
> - Comment construire votre skill Alexa avec AWS + Amazon Developer
> - Testez le skill 
> - Passer la cértification pour la store Amazon Alexa
> - Publier votre skill avant le 13 novembre pour faire parti de l'Alexa Skills Challenge. 

> Le challenge serait suivi par Benoît Nachawati - Technical Evangelist, Amazon Alexa France, qui accompagnera les développeurs à créer des skills engageantes, tout en les guidant dans leur parcours de découverte des interfaces vocales.

*Slides :* https://developer.amazon.com/fr/alexa-skills-kit/alexa-skill-quick-start-tutorial-nodejs
*Projet :* https://alexaskillschallenge.fr.bemyapp.com
*Twitter :* @mariahalse ou @bnachawati

**Comment by PierrickP** [comment]
C'est le format court de https://github.com/parisjs/talks/issues/37 ?

**Comment by Freddy03h** [comment]
Bonjour @MariaWTB, on a un problème avec ce talk, tout porte à croire que c'est un talk à but uniquement promotionnel autour d'un événement sans réel apport technique. Les slides sont une succession d'étapes à cliquer sur la plateforme AWS.

Avez vous plus de précisions concernant le contenu de talk svp ? Car en l'état c'est impossible de le faire passer dans un slot de talk normal. Le talk promotionnel de 5 min en début de meetup est réservé à l'hôte de l'événement.

Merci,

**Comment by MariaWTB** [comment]
Bonjour @Freddy03h pardon je n'avais pas vu a temps le message. D'accord... Le but c'est vraiment pour montrer la facilité de créer une application a commande vocale a partir du node.js et de montrer les possibilités qui existe grâce a ce skills kit - ainsi qu'expliquer les avantages du challenge Alexa Skills. Donc, oui potentiellement un peu promotionnelle. Pas de souci pour le changement, je comprends bien.

**Comment by nachawat** [comment]
Bonjour @PierrickP & @Freddy03h 
Le Challenge sur les Skill Amazon Alexa est terminée. 
Je vous propose de le remplacer par le talk #37 pour permettre aux membres du Meetup de découvrir le SDK Alexa pour Node.js et comment l'utiliser pour développer des skills Alexa
Cette présentation a déjà été proposée et délivrée au [Meetup Node.js Paris](https://www.meetup.com/fr-FR/Nodejs-Paris/events/256405054/) : 
Merci bien,
Benoit
Twitter : @bnachawati
