### ISSUE TITLE
Real-world ReasonReact

### ISSUE THREAD

**Issue by bloodyowl** [parisjs/talks#42]
## Real-world ReasonReact

*Talk format :* Long

*Description :*

Un live coding présentant comment on développe une web app avec ReasonReact. Approche de divers sujets tels que les `Future`, les types `Result`, les `reducerComponents`, les souscriptions et le routing. 

*Slides :* _
*Projet :* _
*Twitter :* https://twitter.com/bloodyowl

**Comment by Freddy03h** [comment]
@bloodyowl hello, on fait un peu de nettoyage dans la liste. Est-ce que c'est un sujet que tu souhaites toujours présenter ? Merci ^^

**Comment by bloodyowl** [comment]
Chaud ouais

**Comment by Freddy03h** [comment]
Hello @bloodyowl es tu disponible pour le meetup du 26 février ? Merci :)

**Comment by bloodyowl** [comment]
Yup
