### ISSUE TITLE
Embauche pour un travail à domicile: évaluateur de médias sociaux H / 

### ISSUE THREAD

**Issue by RecruiterMika** [parisjs/talks#43]
## Embauche pour un travail à domicile: évaluateur de médias sociaux H / 

*Talk format :* Long

*Description :*

> Chez Appen, nous travaillons avec 8 des 10 plus grandes sociétés de technologie du monde pour améliorer et optimiser leurs produits auprès des utilisateurs du monde entier, y compris les plateformes de médias sociaux, les moteurs de recherche, les systèmes de reconnaissance vocale et les sites e-commerce. Le monde de la technologie évolue rapidement et depuis notre création en 1996, nous avons relevé le défi en devenant une société cotée en bourse et en créant une équipe internationale qui travaille depuis plus de 130 pays et dans plus de 180 langues. 

> Vous aimez les médias sociaux et vous souhaitez influencer notre façon d'interagir avec la technologie ? En tant qu'évaluateur de médias sociaux avec Appen, vous avez la possibilité de donner votre avis sur les fils d'actualités, les publicités et les résultats de recherche. Vos idées ont un impact direct sur les services et le contenu des sites de médias sociaux que nous utilisons tous les jours.

> Ce poste peut vous correspondre si : 
> • Vous êtes à la recherche d'un travail flexible pour lequel vous participez à des projets et développez vos compétences 
> • Vous êtes un utilisateur actif et engagé sur des plateformes de médias sociaux telles que Facebook et Instagram 
> • Vous aimez travailler de manière indépendante 
> • Vous souhaitez travailler sur internet depuis votre domicile

> Horaires de travail :
> • Les postes d'évaluateur de médias sociaux sont à temps partiel (jusqu'à 20 heures par semaine) et très flexibles 
> • Le travail habituel nécessite 1 à 4 heures de travail par jour, 5 à 7 jours par semaine

> Qualifications minimales :
> • Résider actuellement en France et être légalement autorisé à y travailler
> • Avoir accès à un ordinateur avec une carte son et des haut-parleurs, et/ou avoir accès à un smartphone de moins de trois ans 
> • Avoir accès à une connexion internet haut débit sécurisée et à un espace de travail calme et non-public 
> • Disposer de bonnes compétences rédactionnelles en anglais 
> • Etre capable de travailler avec des applications, résoudre des problèmes de logiciel et exécuter des consignes de manière indépendante

> Nous sommes fiers de notre équipe diversifiée et de nos offres de travail flexible, et en tant que société cotée en bourse, nous avons obtenu la première place du classement des 100 meilleures entreprises de FlexJobs. Deloitte a également décerné à Appen les prix Technology Fast 500 Asie Pacifique et Technology Fast 50 Australie en 2017.

> Nous sommes un employeur offrant l'égalité des chances et nous valorisons la diversité dans notre entreprise. Nous ne faisons aucune discrimination fondée sur la race, la religion, la couleur, l'origine nationale, le sexe, l'orientation sexuelle, l'âge, l'état matrimonial, le statut d'ancien combattant ou le statut d'invalidité.

*Slides :* https://talent-appen.icims.com/jobs/1056/job?mode=job&iis=Company&iisn=Parisjs_MRobles
*Projet :* https://talent-appen.icims.com/jobs/1056/job?mode=job&iis=Company&iisn=Parisjs_MRobles
*Twitter :*

**Comment by PierrickP** [comment]
Bonjour,
c'est un sujet pour le meetup Paris.js ou un offre d’emplois ?

**Comment by RecruiterMika** [comment]
Bonjour,

Oui, offre d’emplois.

Merci!

Millicent Kane Robles | Recruitment Specialist
[p] +639-555-441003 | Skype: mrobles.appen | appen.com<http://www.appen.com/>
Appen | Join us!<http://join.appen.com/> | Facebook<https://www.facebook.com/lifeatappen> | LinkedIn<https://www.linkedin.com/company/appen> | Twitter<https://twitter.com/lifeatappen> | Blog<http://appen.com/news/>

**Comment by PierrickP** [comment]
Donc, ça n'a absolument *rien* à faire ici.
