### ISSUE TITLE
React-Native Getting started

### ISSUE THREAD

**Issue by thodubois** [parisjs/talks#44]
## React-Native Getting started

*Talk format :* Long

*Description :*

> Présentation de React-Native, par où commencer?
> Qu'est ce qu'Expo?
> Live Coding: Getting started expo app and native app
> What's next?

*Slides :* https://slides.com/fromwood/deck
*Projet :* 
*Twitter :* @ThoDubois

**Comment by PierrickP** [comment]
@thodubois Hello il y a longtemps qu'on a pas eu de React-Native
Est-ce que tu es disponible pour le Paris.js du ** Mercredi 29 mai** ? Merci
Le lien de l’événement https://www.meetup.com/fr-FR/Paris-js/events/260336623/

**Comment by thodubois** [comment]
Yes je serais dispo. Pas de problème pour la presentation. =)

**Comment by PierrickP** [comment]
Cool ! Tu as un compte sur https://www.meetup.com/fr-FR/Paris-js ?

**Comment by thodubois** [comment]
Les slides don't disponibles ici : https://drive.google.com/a/krml.fr/file/d/1g4tFPNlC4Ywrp8QTQlO5vaZGryeIknMj/view?usp=drivesdk
