### ISSUE TITLE
Découverte de protocol-buffers

### ISSUE THREAD

**Issue by izeau** [parisjs/talks#45]
## Découverte de protocol-buffers

*Talk format :* Short

*Description :*

> Un petit talk pour faire découvrir les [Protocol Buffers](https://developers.google.com/protocol-buffers/docs/proto3) avec la bibliothèque [`protocol-buffers`](https://github.com/mafintosh/protocol-buffers). Je n’ai pas encore les slides mais grossièrement le format sera le suivant :

>   * Protocol Buffers : kèssecé
>   * Messages et Typage
>   * Encodage et décodage au runtime
>   * Pré-compilation des fichiers `.proto`

> Je ne suis pas entièrement sûr que ça rentrera dans 5 minutes, une fois que j’aurai un support je ferai évoluer l’issue.

*Slides :* 
*Projet :* https://github.com/mafintosh/protocol-buffers
*Twitter :*

**Comment by Freddy03h** [comment]
@izeau hello, on fait un peu de nettoyage dans la liste. Est-ce que c'est un sujet que tu souhaites toujours présenter ? Merci ^^

**Comment by izeau** [comment]
Salut @Freddy03h ! Non, j'ai laché l'affaire avec les protobuffs. Je ferme le ticket ;)
