### ISSUE TITLE
How-to: Make your application real-time

### ISSUE THREAD

**Issue by jackycute** [parisjs/talks#46]
## How-to: Make your application real-time

*Talk format :* Short (estimate 25 mins)

*Description :*

> If you want to build an online chat room, a multiplayer game, or a collaborative platform in browsers, you need the power of real-time!
> This talk will show you how to build a real-time web application with socket.io and server-send events.
> - What is realtime?
> - What makes web realtime?
> - WebSocket
> - socket.io
> - server-send events
> - HackMD

*Slides :* 
*Projet :* https://hackmd.io
*Twitter :* https://twitter.com/hackmdio

**Comment by jackycute** [comment]
I've shared my slides here:
https://hackmd.io/p/parisjs-realtime

**Comment by jackycute** [comment]
Thanks for inviting @PierrickP

**Comment by PierrickP** [comment]
Yes, i found it.
https://github.com/parisjs/parisjs-website/pull/186

Thanksyou for you talk, i ll come thursday ;)
