### ISSUE TITLE
Property based testing : de la théorie à la pratique

### ISSUE THREAD

**Issue by dubzzz** [parisjs/talks#47]
## Property based testing : de la théorie à la pratique

*Talk format :* Long (30 min)

*Description :*

> Apparu dans le monde fonctionnel avec QuickCheck, le property based testing est une nouvelle approche pour tester le bon fonctionnement d'une application.
Il permet de détecter des bugs en quelques lignes sans avoir à spécifier l'ensemble des cas limites et s'avère être un allié puissant aux tests unitaires classiques.
> Nous verrons ensemble ce qu'est le property based testing.
Par la suite nous déroulerons plusieurs exemples d'application, basés sur le framework fast-check, allant du simple algorithme à l'interface graphique.

*Slides :* https://dubzzz.github.io/fast-check.github.com/talks/meetup-typescript-04092018/property-based-testing.html
*Projet :* https://github.com/dubzzz/fast-check/
*Twitter :* https://twitter.com/ndubien

**Comment by Freddy03h** [comment]
@dubzzz Hello Nicolas, si tu regardes la liste des propositions de talks, il y a des talks qui sont en attentes depuis plus longtemps que le tien…

**Comment by dubzzz** [comment]
@Freddy03h Oui effectivement ^^ Et d'autres moins ;)
Je me posais juste la question pour connaître les critères appliqués et non pour les remettre en cause.

Désolé si mon commentaire a pu être mal interprêté ce n'était en aucun cas l'idée ;)

Je sais par exemple que certains meetups parisiens organisent des sessions par topic particulier, d'autres favorisent la diversité des topics abordés.

**Comment by Freddy03h** [comment]
Ok pas de soucis :)

Alors, on essaye de mixer les sujets, sur un événement mais aussi sur l'ensemble des sessions, et c'est déjà aussi arrivé de faire des spéciales. On s'adapte aussi souvent avec la disponibilité des speakers. Bref c'est pas une science exacte ^^'

On laisse un slot technique à l'hôte de l'événement, et je vois qu'on a Criteo aussi dans la liste des propositions de sponsors, donc on va surement essayer de regrouper ton talk avec l'organisation chez Criteo.

Mais sinon ne t'inquiètes pas ton sujet est totalement compatible ParisJS donc pas de soucis !

**Comment by dubzzz** [comment]
Merci pour ton retour et surement au prochain meetup ParisJS ;)

**Comment by dubzzz** [comment]
Pour information, pour les intéressés, j'ai récemment publié deux articles correspondant à ce thème :
- https://medium.com/criteo-labs/introduction-to-property-based-testing-f5236229d237
- https://medium.com/criteo-labs/detecting-the-unexpected-in-web-ui-fuzzing-1f3822c8a3a5

**Comment by Freddy03h** [comment]
Hello @dubzzz !
Est que tu es dispo pour faire ton talk au meetup du mercredi 25 septembre stp ? Merci :)

**Comment by dubzzz** [comment]
Hello @Freddy03h,
Je ne serai malheureusement pas disponible pour cette édition.
Ça aurait été avec plaisir ;)

**Comment by PierrickP** [comment]
@dubzzz du coup, j'en profite, est-ce que tu es dispo pour l’édition d'après, le **30 octobre** ?

**Comment by dubzzz** [comment]
@PierrickP Parfait 👌 Je serai disponible pour le 30 Octobre

**Comment by Freddy03h** [comment]
@dubzzz  Hello ! Du coup toujours dispo le 30 octobre ? Merci :)

**Comment by dubzzz** [comment]
Toujours OK pour moi 👌

**Comment by Freddy03h** [comment]
20 min de talk c'est ok pour toi ? je viens de voir que tu avais mis 30 min dans la description, c'est pas grave de dépasser un peu (max 25 min) mais ça empiéteras sur les questions du coup.

**Comment by dubzzz** [comment]
Ok, je ferai en sorte de tenir en 20 minutes alors

**Comment by Freddy03h** [comment]
Cool 😄
