### ISSUE TITLE
CodePush: Deploiement d'application de A à Z

### ISSUE THREAD

**Issue by thodubois** [parisjs/talks#49]
## CodePush: Deploiement d'application de A à Z

*Talk format :* Short

*Description :*

> Description et retours d'experience sur CodePush de Microsoft.
>  - Mise en place
>  - Deploiement d'application et de mise à jour  
>  - Avantages / Inconvenient

*Slides :* 
*Projet :* 
*Twitter :* @ThoDubois

**Comment by Freddy03h** [comment]
@thodubois hello, on fait un peu de nettoyage dans la liste. Est-ce que c'est un sujet que tu souhaites toujours présenter ? Merci ^^

**Comment by thodubois** [comment]
@Freddy03h  Yes ça me ferait bien plaisir =)

**Comment by Freddy03h** [comment]
Ok ! Es tu dispo pour le paris.js de janvier, _Mercredi 29 janvier_.
Peux-tu me confirmer ta présence ?

**Comment by thodubois** [comment]
Yes je serais la. Si il reste de la place bien sur =P

**Comment by thodubois** [comment]
Le format court convient? Sinon je peux faire un format long.

**Comment by Freddy03h** [comment]
Aaah j'avais pas noté le format court !
Ben comme tu veux, dis moi si juste 5 minutes te conviennent ou si tu veux un peu plus, mais ça sert à rien de se forcer à faire 20min non plus s'il n'y a pas besoin.

**Comment by thodubois** [comment]
Pas de problème, je veux bien faire 20 min. Ça sera plus intéressant à mon sens

**Comment by Freddy03h** [comment]
Ok top !
