### ISSUE TITLE
Plein la Vue avec JHipster

### ISSUE THREAD

**Issue by sahbi-ktifa** [parisjs/talks#50]
## Plein la Vue avec JHipster

*Talk format :* Long

*Description :*

> Découvrir au travers de JHipster (https://www.jhipster.tech/), une application fullstack avec un front-end entièrement réalisé avec Vue.js. L'idée du talk est de partir de zéro jusqu'au déploiement dans le cloud (sur Heroku par exemple). Très peu de slides donc mais du live coding avec la réalisation d'une véritable application production-ready. Nous pourrons ensuite étudier tous les outils mis en oeuvre par JHipster pour nous aider avec notre application (Spring framework, webpack, BrowserSync, CICD, ... )

*Slides :* 
*Projet :* 
*Twitter :* @SahbiKtifa

**Comment by PierrickP** [comment]
@sahbi-ktifa  Hello, est-ce que tu es disponible pour le Paris.js du ** Mercredi 29 mai** ?
Merci
Le lien de l’événement https://www.meetup.com/fr-FR/Paris-js/events/260336623/

**Comment by sahbi-ktifa** [comment]
Hello, malheureusement non, j'ai prévu de partir le mercredi soir pour le pont qui suit. Je reste dans l'attente d'une prochaine session. Désolé du désagrément.

**Comment by PierrickP** [comment]
OK merci. Pas de souci, ca sera pour une prochaine fois ;)
