### ISSUE TITLE
Integrating AWS Secrets Manager with Kubernetes using Node.js

### ISSUE THREAD

**Issue by JacopoDaeli** [parisjs/talks#52]
## Integrating AWS Secrets Manager with Kubernetes using Node.js

*Talk format :* Long

*Description :*

> During the past six months I have proudly been working on "Kubernetes external secrets".
> The project, initially developed internally at [GoDaddy](https://github.com/godaddy), is now open source under MIT license on the company public Github.
> Kubernetes external secrets is entirely written in Node.js and it integrates external provides such as AWS [Secrets Manager](https://aws.amazon.com/secrets-manager/) with [Kubernetes](https://kubernetes.io/) for securely storing secrets.
> The project extends the Kubernetes API by adding an `ExternalSecret` object using [Custom Resource Definition](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/) and a controller to implement the behavior of the object itself.
 An `ExternalSecret` declares how to fetch the secret data (e.g., fetch property `foo` from AWS Secrets Manager), while the controller converts all `ExternalSecrets` to `Secrets`.
> The conversion is completely transparent to `Pods` that can access `Secrets` normally (e.g., via a volume mount).
> As maintainer, and principal contributor, with this talk I want to present the project and run a demo that practically explains how the system works.
> Trust me, you are going to love it!

_Disclaimer: the link to the project https://github.com/godaddy/kubernetes-external-secrets is not online yet. It will be activated by end of next week Friday 21st December 2018. At the moment, the project is still getting internal final reviews before officially being open sourced and made public on GoDaddy's GitHub._

*Slides :* https://docs.google.com/presentation/d/17hJzgcRqke4gXjKQIF_U8tyR-ssBgi593ZqVKUBVB2M/edit#slide=id.g4e7fa82987_0_58
*Projet :* https://github.com/godaddy/kubernetes-external-secrets
*Twitter :* @JacopoDaeli

**Comment by PierrickP** [comment]
Coucou @JacopoDaeli 
Nice to see you back in Paris.
Ok for january !

**Comment by PierrickP** [comment]
@JacopoDaeli Es-que le lien de ta présentation est ok. nous aurions besoin de la télécharger en local pour tout mettre sur une seule machine
Es-que tu auras besoin absolument d'internet ?

**Comment by JacopoDaeli** [comment]
@PierrickP meet up is tomorrow right? Slides: https://docs.google.com/presentation/d/17hJzgcRqke4gXjKQIF_U8tyR-ssBgi593ZqVKUBVB2M/edit#slide=id.g4e7fa82987_0_58

**Comment by JacopoDaeli** [comment]
@PierrickP btw, I need to use my computer since I have a demo to show as well. Is that ok?
And yes I need Internet.
