### ISSUE TITLE
Animations : comment atteindre rapidement le standard du marché, et au delà

### ISSUE THREAD

**Issue by Minishlink** [parisjs/talks#53]
## Animations : comment atteindre rapidement le standard du marché, et au delà

*Talk format :* Long

*Description :*

> Retour d'expérience sur plusieurs mois d'apprentissages sur les animations en React Native. Quelles sont les clés pour proposer une expérience fluide et cohérente ? Comment fait-on cela techniquement de la plus rapide façon ? Nous allons partir d'animations simples et peu visibles, mais qui, quand elles ne sont pas présentes, font taches. Et nous finirons par des animations plus complexes et "wahou" !

*Slides :* 
*Projet :* 
*Twitter :* @Minishlink

**Comment by PierrickP** [comment]
@Minishlink Coucou 👋 est-ce que tu es disponible pour le Paris.js du Mercredi 29 mai ?

Le lien de l’événement https://www.meetup.com/fr-FR/Paris-js/events/260336623/

**Comment by Minishlink** [comment]
Hello @PierrickP, yes je serai dispo :)
