### ISSUE TITLE
CSS, préprocesseurs, BEM, CSS Modules, Styled Components... comment choisir ?

### ISSUE THREAD

**Issue by AlbericTrancart** [parisjs/talks#54]
## CSS, préprocesseurs, BEM, CSS Modules, Styled Components... comment choisir ?

*Talk format :* Long

*Description :*

> L'environnement CSS a bien évolué au fur et à mesure de ces 20 dernières années. Cependant, il semble toujours difficile d'écrire du CSS fonctionnel et maintenable : en 2019, que choisir pour son projet afin d'y arriver ? Avec un processus qui se veut le plus objectif possible, nous établirons une checklist de ce qu'est une bonne stack CSS afin de choisir les technos qui vous conviendront le mieux.

*Slides :*
*Projet :*
*Twitter :* @alberictrancart

**Comment by PierrickP** [comment]
@AlbericTrancart Hello, est-ce que tu es disponible pour le Paris.js du ** Mercredi 29 mai** ?
Merci
Le lien de l’événement https://www.meetup.com/fr-FR/Paris-js/events/260336623/

**Comment by Freddy03h** [comment]
@AlbericTrancart up ?

**Comment by Freddy03h** [comment]
@AlbericTrancart up ?

**Comment by AlbericTrancart** [comment]
@PierrickP @Freddy03h Hello ! Je ne serai pas dispo le 29 mai. Par contre toujours chaud pour un éventuel meetup d'après. Pour info je ne lis pas les notifs Github mais le ping Twitter a bien fonctionné :)

**Comment by PierrickP** [comment]
@AlbericTrancart  Hello es-que tu peux me confirmer ta presence pour le meetup du **25 septembre** ?
