### ISSUE TITLE
Comment j'ai fait décoller mon projet perso : une app web et desktop cross-platform

### ISSUE THREAD

**Issue by foucdeg** [parisjs/talks#55]
## Comment j'ai fait décoller mon projet perso : une app web et desktop cross-platform

![x-plane](https://trello-attachments.s3.amazonaws.com/549abb0c59b88a94f6251307/5b421c9dfd38f782b52b2ebf/fb1f1811bfeeb3ef9a85d8aa77ef345c/9MMkNXV.jpg)

*Talk format :* Long

*Description :*

Je vous propose un REX de mon principal projet perso depuis 3 ans. C'est une application web et desktop compagnon du simulateur de vol X-Plane. 
Comment on fait pour coder une app web + desktop cross-platform ? Comment on la met en prod, comment on la met à jour, comment on la sécurise ?

Et aussi, on va piloter des avions.

*Slides :* [WIP] https://slides.com/foucaulddegeorges/electron
*Projet :* https://airspaces.app/
*Twitter :* https://twitter.com/foucdeg

**Comment by PierrickP** [comment]
@foucdeg ca a l'air sympa ;)

**Comment by PierrickP** [comment]
la 2 ?

**Comment by foucdeg** [comment]
ok ! je pars sur la 2.

**Comment by PierrickP** [comment]
@foucdeg Hello, est-ce que tu es disponible pour le Paris.js du ** Mercredi 29 mai** ?
Merci
Le lien de l’événement https://www.meetup.com/fr-FR/Paris-js/events/260336623/

**Comment by Freddy03h** [comment]
@foucdeg up ?

**Comment by foucdeg** [comment]
@PierrickP @Freddy03h malheureusement non, je suis en mission au maroc jusqu'à début juin. La date du suivant est-elle connue ?

**Comment by PierrickP** [comment]
@foucdeg 28 aout ou 25 septembre

**Comment by foucdeg** [comment]
@PierrickP ok pour septembre !

**Comment by foucdeg** [comment]
@PierrickP Toujours OK de votre côté pour le 25 ?

**Comment by foucdeg** [comment]
Ping @PierrickP @Freddy03h , est-ce que c'est toujours ok de votre côté pour le 25 ?

**Comment by PierrickP** [comment]
@foucdeg on a pas encore planifié le prochain meetup.
C'est certain qu'il y aura un evenement, mais j'ai pas encore les détails

**Comment by foucdeg** [comment]
Ok, tenez moi au courant :)

**Comment by PierrickP** [comment]
@foucdeg Hello es-que tu peux me confirmer ta presence pour le meetup du **25 septembre** ?

**Comment by foucdeg** [comment]
@PierrickP un peu short notice, mais oui ok.

Pour pouvoir faire la démo en même temps que les slides, il me faudrait pouvoir afficher les écrans de 2 PC simultanément, et un PC de prêt que je puisse utiliser pour les slides (le mien servira à faire tourner le simulateur). Est-ce que c'est jouable ?

**Comment by Freddy03h** [comment]
Hello, je pense que ça va être compliqué, souvent les salles n'ont qu'un seul video projecteur. Et celles qui en ont deux ou plus dans une grande salle équipée pour, n'ont qu'un seul input video.

Tu n'as pas moyen de basculer sur entre 2 écrans depuis ta machine ? Comme ça tu peux basculer entre tes slides et ta demo à ta guise pendant la présentation.

**Comment by foucdeg** [comment]
ok, je réfléchis à une autre moyen alors
