### ISSUE TITLE
React JS / GraphQL expliqués aux développeurs Back-End (Symfony, Node.js...)

### ISSUE THREAD

**Issue by devon39** [parisjs/talks#56]
## React JS / GraphQL expliqués aux développeurs Back-End (Symfony, Node.js...)

*Talk format :* Long

*Description :*

> Etant développeur Back-End (Symfony / Node.js) et connaissant l'API Rest, il s'agit de vous apporter des éclairages sur la librairie React JS et sur le langage de requêtes GraphQL. 
> A travers de l'exposé seront développées toutes les facettes de ces outils. 

*Slides :*
[GraphQL _ React Js Expliqué aux devs backend.pdf](https://github.com/parisjs/talks/files/2809486/GraphQL._.React.Js.Explique.aux.devs.backend.pdf)

**Comment by PierrickP** [comment]
@devon39  Es-que tu peux mettre le lien de ta présentation. Apparemment, vous n'avez pas internet, on va centraliser sur une seul machine

**Comment by devon39** [comment]
Bonsoir,
Je vais m'en occuper et je t'enverrai lelien.
Bonne fin de journée à toi

Le mar. 29 janv. 2019 à 18:12, Pierrick PAUL <notifications@github.com> a
écrit :

**Comment by devon39** [comment]
C'est fait !

Le mar. 29 janv. 2019 à 18:19, Christ J <christophe.jolas@gmail.com> a
écrit :
