### ISSUE TITLE
5 astuces pour rendre votre application web mobile friendly

### ISSUE THREAD

**Issue by LaurentRos** [parisjs/talks#57]
## 5 astuces pour rendre votre application web mobile friendly

*Talk format :* Long

*Description :*

> Boostez votre application web en lui donnant des features d'application native.
> Je vous présenterai comment transformer votre application en Progressive Web App et implémenter des Web Sockets pour :
> - ajouter l'application à votre homescreen pour améliorer la rétention
> - cacher les assets et calls API pour permettre une utilisation offline et améliorer la vitesse de chargement
> - créer des push notifications pour fidéliser vos utilisateurs
> - activer la background synchronisation pour permettre les interactions offline
> - toujours afficher la data la plus récente sans rafraichissement manuel

*Slides :* 
*Projet :* 
*Twitter :* @lros_8

**Comment by PierrickP** [comment]
@LaurentRos Coucou 👋 est-ce que tu es disponible pour le Paris.js du **Mercredi 29 mai** ?

Le lien de l’événement https://www.meetup.com/fr-FR/Paris-js/events/260336623/

**Comment by LaurentRos** [comment]
Non je serai en vacances à cette date ... Sorry =/

**Comment by PierrickP** [comment]
@LaurentRos  Hello es-que tu peux me confirmer ta présence pour le meetup du **25 septembre** ?

**Comment by PierrickP** [comment]
@Freddy03h pas dispo pendant les 2 prochains mois, on remets en todo

**Comment by mauricesvay** [comment]
@LaurentRos hello, est-ce que tu es dispo pour faire ce talk ce mois-ci, le mercredi 27 novembre?

**Comment by LaurentRos** [comment]
Hello @mauricesvay 

Sorry, pour le moment je n'ai pas prévu de refaire le talk =/
Je vais fermer l'issue. Je vous referai signe pour les prochains talks =)

Bon courage !

**Comment by mauricesvay** [comment]
@LaurentRos bien noté! On va trouver un autre talk pour ce mois-ci!
