### ISSUE TITLE
Comprendre la conversion de type en JavaScript

### ISSUE THREAD

**Issue by laruiss** [parisjs/talks#59]
## La conversion de type en JavaScript

*Talk format :* Long

*Description :*

> Est-ce que tout est objet en JavaScript ?
> Vaut-il vraiment mieux utiliser === plutôt que == ? Pourquoi ?
> Pourquoi [] + [] donne une chaîne vide ?
> Pourquoi [] + {} ne donne pas la même chose que {} + []?
> Quand a lieu la conversion de type en JavaScript ?
> Est-ce qu'elle est logique ou est-ce que c'est le mal ?

> Venez dédiaboliser la conversion de type en JavaScript lors de ce talk !

*Slides :* https://slides.com/stormier/type-coercion-in-js
*Projet :* 
*Twitter :* @laruiss

**Comment by Freddy03h** [comment]
Hello @laruiss !
Est que tu es dispo pour faire ton talk au meetup du mercredi 25 septembre stp ? Merci :)

**Comment by laruiss** [comment]
Bonjour @Freddy03h,

Oui, je suis disponible

**Comment by Freddy03h** [comment]
Top ! Je te confirme alors pour le Paris.js 25 ^^

**Comment by laruiss** [comment]
Très bien, merci !

À bientôt

Le mar. 17 sept. 2019 à 14:27, Freddy Harris <notifications@github.com> a
écrit :
