### ISSUE TITLE
FoalTS: elegant and all-inclusive Node.Js web framework based on TypeScript.

### ISSUE THREAD

**Issue by LoicPoullain** [parisjs/talks#60]
## FoalTS: elegant and all-inclusive Node.Js web framework based on TypeScript.

*Talk format :* Long

*Description :*

> FoalTS is a Node.JS framework for building web applications. It offers many ready-made components out of the box, has an elegant syntax and is written in TypeScript. More information [here](https://foalts.org/docs).

![image](https://user-images.githubusercontent.com/13604533/104697341-eac77c00-570f-11eb-9f6e-9ef174d87281.png)

*Slides :* Not yet!
*Projet (website) :* https://foalts.org/
*Projet (Github) :* https://github.com/FoalTS/foal
*Twitter :* https://twitter.com/foalts

**Comment by mauricesvay** [comment]
Hello @LoicPoullain  !

Merci d'avoir proposé un sujet. On envisage de relancer les meetups dans une formule 100% en ligne, avec des talks un plus courts (10-15 minutes).

- Est-ce que ton sujet est toujours d'actualité?
- Est-ce qu'il pourrait être adapté à un format plus court?

**Comment by LoicPoullain** [comment]
Hello!



>     * Est-ce que ton sujet est toujours d'actualité?

Oui



>     * Est-ce qu'il pourrait être adapté à un format plus court?

Oui
