### ISSUE TITLE
Développer des structures de données en JavaScript

### ISSUE THREAD

**Issue by Yomguithereal** [parisjs/talks#62]
## Développer des structures de données en JavaScript

*Talk format :* Long

*Description :*

There is a tenacious misconception nowadays that people working with JavaScript do not need to know much about data structures because developing for the web is still often deemed to be, and this cannot be more false, an easier task than "real" programming.

Web applications have become complex beasts and node.js allows to build programs that used to be other backend languages' turf. JavaScript developers now need to develop, as with any other programming language, custom data structures to solve particular problems when arrays and objects are simply not enough. The intention of this presentation is therefore to compile series of tips, tricks and use cases regarding the implementation of data structures in JavaScript and the challenges it poses. It is indeed tricky to ensure consistent performance in a high-level language with JIT and where engines like v8 apply a lot of optimization magic. One has to be able to evolve around those constraints. Examples will be taken from libraries such as graphology, sigma.js' newest version and finally mnemonist to demonstrate that 1. performant data structures can be designed for JavaScript using the language's capabilities and that 2. everyone can use them to solve problems more efficiently.

*Slides :* https://yomguithereal.github.io/mnemonist/presentations/fosdem2019/#0
*Projet :* https://fosdem.org/2019/schedule/event/data_structures_javascript/
*Twitter :* https://twitter.com/Yomguithereal

Le talk a été donnée au FOSDEM cette année en anglais mais je peux la donner en français sans aucun problème.

**Comment by mauricesvay** [comment]
@Yomguithereal hello, est-ce que tu es dispo pour faire ce talk ce mois-ci, le mercredi 27 novembre?

**Comment by Yomguithereal** [comment]
Bonjour @mauricesvay, c'est tout à fait possible pour moi de faire ce talk le mercredi 27 novembre. Je vais essayer de rafraîchir et traduire les slides d'ici là.

**Comment by PierrickP** [comment]
Super ! Je pense pas que la traduction des slides soit obligatoire

**Comment by mauricesvay** [comment]
@Yomguithereal top, je pense que les slides en anglais c'est même mieux. Ça permet aux anglophones de suivre un peu :)

**Comment by Yomguithereal** [comment]
Ok. Je vais juste passer rafraîchir 2-3 trucs alors.

**Comment by mauricesvay** [comment]
@Yomguithereal est-ce que tu as besoin de trucs particuliers pour ta présentation ce soir? Tu pourras tester la projection avant qu'on commence. Sinon, j'aurais mon ordinateur au cas où.

**Comment by Yomguithereal** [comment]
Bonjour @mauricesvay, n'importe quel ordinateur devrait faire l'affaire vu que les slides sont en ligne ici: https://yomguithereal.github.io/mnemonist/presentations/fosdem2019

Je peux emmener mon ordinateur si besoin mais je préfèrerais éviter.
