### ISSUE TITLE
Intégration du widget Relais Colis à un site Drupal

### ISSUE THREAD

**Issue by guacamelo** [parisjs/talks#63]
## Intégration du widget Relais Colis à un site Drupal

*Talk format :* Long

*Description :*

> Bonjour,
> Je souhaite intégrer le widget Relais Colis (php & js) à ma boutique en ligne qui tourne sur Drupal 7.x.
> J'ai obtenu quelques lignes de code de Relais Colis. Elles permettent notamment d'obtenir la liste des points relais à choisir.
> Mais cela sort des limites de ma connaissance.
> Avez vous des pistes ou un aide à me proposer svp?
> Merci d'avance
> K

*Slides :* 
*Projet :* https://www.thala.fr
*Twitter :*

**Comment by PierrickP** [comment]
Bonjour,
Sauf erreur, ce n'est pas un talk ?
