### ISSUE TITLE
Mise à l’échelle d’une application web

### ISSUE THREAD

**Issue by ericlemerdy** [parisjs/talks#64]
## Mise à l’échelle d’une application web

*Talk format :* Long

*Description :* d’un monolithe AngularJS à une application React modulaire

> "Il me faut un mois de refacto avant de commencer le dev…”, "C’est bon, je finis au prochain sprint" (dit pareil depuis 3 mois), "C’est du code legacy, ça" (fait au sprint dernier). Je suis sur que vous avez déjà entendu ça quelque part... Dans cette présentation, je décris le niveau de qualité dans notre web app AngularJS qui n'a pas grossi très sereinement. Des événements, des références d'objets javascript, des scopes de composants, des états dans des services angular, etc.
> Comment s'est-on réveillé de ce cauchemard ? Vous verrez comment Redux a stabilisé la gestion de l'état applicatif, React a introduit un meilleur design orienté composant et amélioré la performance et enfin, comment RxJS a découplé le cycle de vie des composants de celui des données !

*Slides :* _pas encore publiés_
*Projet :* https://one2team.com
*Twitter :* https://twitter.com/ericlemerdy

**Comment by ericlemerdy** [comment]
Talk donné la semaine dernière chez [42School](https://github.com/42School) :smiley:

**Comment by ericlemerdy** [comment]
Talk donné [la semaine dernière](https://www.linkedin.com/feed/update/urn:li:activity:6498570333946212353/) chez [42School](https://github.com/42School) :smiley:

**Comment by denisbarthelemy** [comment]
Super talk qui a trouvé du répondant chez 42 !

**Comment by marekkalnik** [comment]
Hâte de voir RxJS implémenté dans un vrai projet, et pas juste un tuto !

**Comment by flegall** [comment]
Hâte de voir ça ç

**Comment by ericlemerdy** [comment]
> Hâte de voir ça !

La pression monte 🌋 !

**Comment by mauricesvay** [comment]
@ericlemerdy est-ce que tu serais dispo pour faire ce talk ce mois-ci le 27 novembre chez Alan?

**Comment by ericlemerdy** [comment]
Oui avec plaisir ! On a même amélioré cette présentation avec mon collègue !

**Comment by mauricesvay** [comment]
@ericlemerdy top, à mercredi 27 !

**Comment by mauricesvay** [comment]
@ericlemerdy est-ce que tu as besoin de trucs particuliers pour ta présentation ce soir? Tu pourras tester la projection avant qu'on commence. Sinon, j'aurais mon ordinateur au cas où.

**Comment by ericlemerdy** [comment]
C'est une présentation Google, donc l'un ou l'autre m'ira 👍 à tout à l'heure !Le 27 nov. 2019 13:31, Maurice Svay <notifications@github.com> a écrit :@ericlemerdy est-ce que tu as besoin de trucs particuliers pour ta présentation ce soir? Tu pourras tester la projection avant qu'on commence. Sinon, j'aurais mon ordinateur au cas où.
