### ISSUE TITLE
React Fiber : une innovation discrète, des implications retentissantes

### ISSUE THREAD

**Issue by FBerthelot** [parisjs/talks#65]
## React Fiber : une innovation discrète, des implications retentissantes

*Talk format :* Long

*Description :*

> L’équipe de React a fait de nombreuses annonces à propos de nouvelles APIs ces derniers temps. On parle de : Suspense, Lazy Hooks, Error Boundaries, Time Slicing ou encore Concurrent React.

> Il y a des choses particulièrement intéressantes comme de nouveaux patterns de programmation qui pourraient changer la manière de coder des interfaces dans le futur. Mais il faut avouer qu’il peut devenir difficile de suivre toutes les évolutions proposées et en comprendre la direction.

> L’effervescence autour des nouvelles fonctionnalités a pour origine la ré-implémentation du moteur de React dans sa version 16 : nom de code React Fiber (sorti en septembre 2017). Cette refonte très technique n’a pas fait de buzz et n’a rien changé directement dans l’API. Elle a en revanche libéré un potentiel incroyable pour trouver de nouveaux concepts que Facebook ajoute petit à petit dans sa bibliothèque.

> Nous vous proposons de reprendre le sujet dans l’ordre : qu’est ce que React Fiber ? Qu’est ce qui change dans le moteur et ce que cela veut dire pour vous ? Nous nous intéresserons ensuite à chacune des nouveautés (Suspense, Lazy, Hooks, Error Boundaries, Time Slicing, ...) pour en détailler le fonctionnement, ce que cela apporte et son lien avec Fiber. Nous illustrerons le code avec démo d’une arène de pokemon !

*Slides :* https://docs.google.com/presentation/d/1AaKnJZOQjg5q6YifQXO0cVVUcbhAVD-dJBjVCCG0_B0
*Projet :* https://github.com/Swiip/pokemon-arena
*Twitter :* @berthel350 & @swiip

**Comment by mauricesvay** [comment]
Hello @FBerthelot  !

Merci d'avoir proposé un sujet. On envisage de relancer les meetups dans une formule 100% en ligne, avec des talks un plus courts (10-15 minutes).

- Est-ce que ton sujet est toujours d'actualité?
- Est-ce qu'il pourrait être adapté à un format plus court?

**Comment by FBerthelot** [comment]
Hello @mauricesvay !

De rien :)

Je pense que ce talk n'est malheureusement plus d'actualité. Je vais donc fermer cette PR.

Mais c'est noté pour le nouveau format, peut-être que je proposerai un autre talk plus court sur un autre sujet ;)

A bientôt !

**Comment by mauricesvay** [comment]
@FBerthelot ça marche, merci d'avoir mis à jour l'issue !
