### ISSUE TITLE
WebAssembly va tuer JS (ou pas)

### ISSUE THREAD

**Issue by vdeturckheim** [parisjs/talks#68]
## WebAssembly va tuer JS (ou pas) 

*Talk format :* Long

*Description :*

Bon, WebAssembly, c’est le nouveau cool kid du quartier. Combien de fois on a entendu des collègues balancer un “nan mais bientôt avec WebAssembly on aura plus à subir JS”.
Mais est-ce bien vrai ? WebAssembly (WASM de son petit nom) va-t-il mettre fin à plusieurs décennies de règne sans partage de JS sur les browsers ? 
Mais d’ailleurs, c’est quoi WASM ?
Quel est le rapport avec Rust ?
Et avec TypeScript ?
Qui est le Chevalier Blanc ?
Qui a volé l’orange du marchand ?

On répondra à certaines de ces questions… mais lesquelles ?

*Twitter :* **https://twitter.com/poledesfetes**

**Comment by topheman** [comment]
Si tu veux profiter d'un exemple simple mais complet sur rust / wasm, j'ai publié un projet à ce propos en janvier : https://github.com/topheman/rust-wasm-experiments

Je pensais faire un talk à ce propos, peut-être qu'on pourrait faire quelque chose de complémentaire ?

Tophe

**Comment by vdeturckheim** [comment]
Excellent! 

Mon talk est assez bas niveau en vrai, du coup ca se goupille tres bien avec un talk apres sur un projet rust-wasm.
