### ISSUE TITLE
Faites bien plus que des tests avec votre CI tout en la maintenant sous les 5 minutes

### ISSUE THREAD

**Issue by Ojisama** [parisjs/talks#71]
## Faites bien plus que des tests avec votre CI tout en la maintenant sous les 5 minutes

*Talk format :* Long

*Description :*

> Lassé de devoir attendre plus de 10 minutes la fin d'un build qui ne faisait que tester ma codebase, j'ai décidé d'améliorer la CI de mon projet Web.  J'ai divisé le temps de CI par 2, et en bonus j'ai automatisé des tâches fastidieuses et répétitives pour mon équipe sans rallonger le build.

> Durant ce talk, je vous présenterai la recette pour une CI intelligente et efficace :

> - les workflows CircleCI pour paralléliser vos tâches
> - l'automatisation du déploiement et de la publication de librairies
> - l'ajout d'outils externes comme Danger et BundleSize pour monitorer la santé de votre codebase

> Cette recette a déjà pu aider plusieurs équipes en interne. Vous pourrez l'appliquer à votre projet, et vos collègues seront ravis des changements que vous pourrez apporter à votre CI!

*Slides :* 
*Video :* https://drive.google.com/file/d/10pTySBun0SvRP8zvM5Ms6D5JDR5mO6CY/view?usp=sharing
*Projet :* 
*Twitter :* @aurelien__lm

**Comment by hubertlaverny** [comment]
Hate d'entendre de talk et d'améliorer la perf de ma CI 🎉

**Comment by Freddy03h** [comment]
@hubertlaverny Vous répétez pas vos talks en interne chez Theodo ? Vous devriez c'est une bonne pratique de s'entrainer devant ses collègues pour avoir des retours.

**Comment by Ojisama** [comment]
@Freddy03h Si, mais @hubertlaverny n'était pas encore arrivé lorsque j'ai fait le talk à Theodo :smiley:

**Comment by Ojisama** [comment]
Voici la vidéo de la première version du talk https://drive.google.com/file/d/10pTySBun0SvRP8zvM5Ms6D5JDR5mO6CY/view?usp=sharing

**Comment by PierrickP** [comment]
Hello @Ojisama 
On aimerait sélectionner ton sujet pour le paris.js de janvier, *Mercredi 29 janvier*.
Peux-tu me confirmer ta presence ?

**Comment by Freddy03h** [comment]
Hello, petit up @Ojisama ?

**Comment by Ojisama** [comment]
Hello @Freddy03h et @PierrickP , je serai ravi de présenter ce sujet le 29 janvier prochain :)

**Comment by Ojisama** [comment]
Slides : https://slides.com/aurelienlemasson/formation-une-ci-qui-dechire
