### ISSUE TITLE
Tester n’importe quel code, même le code dont vous n’êtes pas fier!

### ISSUE THREAD

**Issue by PierrickP** [parisjs/talks#72]
## Mon titre

*Talk format :* Long

*Description :*

>Sous-titre: Une approche pragmatique au test de code legacy (code dont on pense qu’il n’est pas testable et que personne veut toucher).
>En utilisant des mock simples et des design patterns, en javascript.
>
>Avez vous déjà entendu quelque chose comme:
>> “C’est pas grave, on teste pas ce code là.”
>> “T’es sûr de vouloir toucher ce code? Tu risque de casser quelque chose!”
>
>Ça a un air de déjà vu, n’est-ce pas?
>La pluspart du temps en plus, les deux situations parlent du même code.
>
>La majorité du code a une date d’expiration, plus ou moins dans le futur.
>Ce talk est là pour vous aider lorsque cette date a été dépassée.
>Même dans le cas où cette date a été dépassée pour si longtemps que le code est devenu ce monstre de spaghetti moisi qui sent tellement mauvais que vous en avez peur et que tout ce que vous voulez c’est le jeter à la poubelle (mais vous en avez trop peur).
>
>Ce talk va vous aider à éviter de “casser quelque chose” et “make your code great again”.
Vous allez même pouvoir aider les futurs aventuriers qui s’égareront dans ce code: le code que vous écrivez aujourdhui est le code légacy de demain.
>Es-ce que vous voulez faire encore plus le bazar?
>Ou es-ce que vous voulez avoir du code plus robuste qui aidera les générations futures?

*Slides :* 
*Projet :* 
*Twitter :* @wgorgedev

**Comment by WilliamGorge** [comment]
lien vers les slides: https://docs.google.com/presentation/d/1B6zk3VjbsveVcDgq5mKJ1EP2buhBk9auDVh77jQPLsU/edit#slide=id.p

désolé j'avais zappé de le faire :/
