### ISSUE TITLE
Implementing complex design systems in your front-end

### ISSUE THREAD

**Issue by MindRave** [parisjs/talks#73]
## Implementing complex design systems in your front-end

*Talk format :* Short

*Description :*

> As companies work on features and evolve their product, design systems become increasingly used and front-end engineers find themselves working with atomic components more and more. Our goal is to make our front-end components into our single source of truth, instead of the sketch files, and we'd like to share a few thoughts on how we're going about it.

*Slides :* 
*Projet :* 
*Twitter :* @aircalltech/@MindRave

**Comment by Freddy03h** [comment]
@MindRave Est ce bien un talk court (5min) ou un long (20min) ?

**Comment by Freddy03h** [comment]
ping @MindRave !

**Comment by Freddy03h** [comment]
Talk long, et validé
