### ISSUE TITLE
An introduction to webassembly

### ISSUE THREAD

**Issue by eliamaino-fp** [parisjs/talks#74]
## An introduction to webassembly

*Talk format :* Long

*Description :*

**A brief introduction to the amazing world of webassembly!**

- Short overview on how JS engines work (JIT compilers, etc.)
- Short overview on how memory management works in JS
- What is webassembly
- How can I start playing with it
- Current status and future development of this technology

The talk is intended to be an introduction about the core ideas behind the whole webassembly echosystem, it will not include examples from personal projects.

The talk will be in English ;) 

*Slides :* 
*Projet :* 
*Twitter :* @eliamain

**Comment by PierrickP** [comment]
Hello, can you update your description with your sides link.
We ll make a spacial event about WASM with https://github.com/parisjs/talks/issues/68 and https://github.com/parisjs/talks/issues/69, i would like to check if all talks are complementary

Thanks

**Comment by eliamaino-fp** [comment]
Hi @PierrickP, honestly I didn’t work on any slides yet (since I was waiting for a confirmation before starting any work).

Aaaanyway, good to hear that you plan to organize a full WebAssembly edition. Regarding the compatibility with the other talks, we can set up a communication channel with the other speakers in order to avoid any topic overlap.

(Regarding the slides, probably for the JIT part I will maybe take inspiration from a talk  I
