### ISSUE TITLE
Au-delà de la pagination : rendre vos tableaux React performants grâce au windowing

### ISSUE THREAD

**Issue by edwandr** [parisjs/talks#75]
## Au-delà de la pagination : rendre vos tableaux React performants grâce au windowing

*Talk format :* Short

*Description :*

Si vous avez déjà essayé d'afficher un tableau contenant beaucoup d'éléments en React, vous savez probablement que cela peut très vite dégrader les performances de votre site. Nous allons aborder les techniques suivantes pour améliorer les performances :

- Une solution simple : la pagination
- Privilégier l'UX : Le lazy loading et ses pièges
- Le windowing : le meilleur des deux mondes ?

Dans ce talk, je souhaite vous donner les clés pour construire des tableaux performants du premier coup.

*Slides :* à venir
*Twitter :* https://twitter.com/elie_dutheil

**Comment by Freddy03h** [comment]
Hello @edwandr es tu disponible pour le meetup du 26 février ? Je pense qu'on a une place pour un talk court de 5 min, Merci :)

**Comment by Freddy03h** [comment]
Ping @edwandr !

**Comment by edwandr** [comment]
Hello @Freddy03h, désolé pour la réponse tardive. Oui pas de souci, mon talk était plus prévu pour durer 10 minutes mais je pense pouvoir le raccourcir

**Comment by Freddy03h** [comment]
Ok, si on commence à l'heure et qu'on enchaine bien les talks ça devrait le faire ^^
