### ISSUE TITLE
Fast 2D rendering graphs with d3.js & canvas optimization

### ISSUE THREAD

**Issue by buenjybar** [parisjs/talks#78]
## Fast 2D rendering graphs with d3.js & canvas optimization

*Talk format :* Long 

*Description :*
> 2D graphs are now made easy to implement with this awesome **d3.js** library,
> but when you start to add **User interactions** and a large **amount of data**, SVG rendering is getting slow and doesn't fit your needs anymore...
> 
> Welcome to you, **Mr. Canvas**!!
> We will implement a solution to get the best out of the SVG and Canvas.
> 
> Canvas:
> pros: fast rendering,
> cons: hard to interact with
> 
> SVG :
> pros: easy to interact with
> cons: heavy, slow are rendering + change DOM?

*Slides :* (TBD)
*Projet :* https://cardiologs.com
*Twitter :* https://twitter.com/buenjy

**Comment by mauricesvay** [comment]
Hello @buenjybar !

Thanks for submitting your talk. We are considering starting meetups again, but fully online with shorter talks (10-15 minutes) 

- Is the talk still relevant?
- Can it be done in a shorter amount of time?

**Comment by buenjybar** [comment]
Yes I think i can make it fit in 10 to 15min

**Comment by buenjybar** [comment]
Do you know when will be this presentation ? so I can prepare everything on my side

**Comment by mauricesvay** [comment]
@buenjybar we are just trying to evaluate if talks can work with the new online format at the moment. Your talk hasn't been selected for a meetup yet. We'll give you a heads up when it is :)

**Comment by Freddy03h** [comment]
Hello @buenjybar ! Est ce que tu es dispo pour le prochain parisJS du mercredi 31 mars ? Merci !

**Comment by buenjybar** [comment]
Malheureusement non 😟

**Comment by Freddy03h** [comment]
Ok pas de soucis, merci de ta réponse ^^

**Comment by Freddy03h** [comment]
Hello @buenjybar  ! On tente de relancer les meetups, est ce que tu serais dispo le mercredi 24 novembre pour nous proposer ton talk ? Merci 😀

**Comment by Freddy03h** [comment]
Alors, on va revenir à un évènement physique, donc un format de 20 minutes maximum convient très bien ! (mais pas obligé d'allonger si pas besoin, un talk de 15 min c'est très bien aussi !)

**Comment by buenjybar** [comment]
The slides : https://docs.google.com/presentation/d/1QlEr0J8RmSVTfS-suBqRc6Gx17ukPYtl_jhGp193-Zw/edit#slide=id.gfc81a3bcbb_0_144

The code example https://github.com/buenjybar/SVG-Canvas
