### ISSUE TITLE
Hello, null!

### ISSUE THREAD

**Issue by bloodyowl** [parisjs/talks#79]
## Hello, null!

*Talk format :* Short

*Description :* 

> fixing optionality using types

La nature de `null` et `undefined` pose des soucis dans la gestion de "l'optionalité" dans le code. Les exceptions présentent d'autres soucis dans la gestion du succès d'une opération. 

Présentation des types `Option` et `Result`.

https://putaindecode.io/articles/le-type-option-c-est-quoi-et-ca-regle-quel-probleme

*Twitter :* https://twitter.com/bloodyowl

**Comment by mauricesvay** [comment]
Hello @bloodyowl !

Merci d'avoir proposé un sujet. On envisage de relancer les meetups dans une formule 100% en ligne, avec des talks un plus courts (10-15 minutes).

- Est-ce que ton sujet est toujours d'actualité?

**Comment by bloodyowl** [comment]
Sure 😄

**Comment by mauricesvay** [comment]
@bloodyowl  ton talk a été retenu pour le meetup du mercredi 3 février 19h. Est-ce que tu pourrais confirmer si c'est OK pour toi?

**Comment by bloodyowl** [comment]
No problem!

Pour info le titre définitif depuis le temps, c'est "Simplifier la gestion de l'UI avec les types (algébriques)" maintenant (mais le sujet est le même).

**Comment by mauricesvay** [comment]
@bloodyowl top ! Est-ce qu'il y a un mail où je peux t'envoyer les détails du déroulement ?
