### ISSUE TITLE
Prouvez votre code avec Typescript

### ISSUE THREAD

**Issue by sebsheep** [parisjs/talks#81]
## Prouvez votre code avec Typescript

*Talk format :* Long

*Description :*

"Prouvez du code", ça vous paraît tordu ? Et pourtant, c'est une technique extrêmement efficace pour bâtir des applications robustes. Dans ce talk, nous verrons comment utiliser des concepts très simples de typage pour apporter des garanties solides dans le code que vous écrivez en Typescript.

**Comment by mauricesvay** [comment]
Hello @sebsheep !

Merci d'avoir proposé un sujet. On envisage de relancer les meetups dans une formule 100% en ligne, avec des talks un plus courts (10-15 minutes).

- Est-ce que ton sujet est toujours d'actualité?
- Est-ce qu'il pourrait être adapté à un format plus court?

**Comment by sebsheep** [comment]
Hello @mauricesvay !

Merci pour le retour. J'ai changé le contenu de ce que je voulais proposer, et je peux faire tenir ça en 15 minutes (difficilement moins :) )

**Comment by mauricesvay** [comment]
Merci pour l'update. On te recontactera si le sujet est retenu pour un futur meetup !

**Comment by mauricesvay** [comment]
@sebsheep je sais que c'est un peu à la dernière minute, mais est-ce que ça te dirait de présenter au meetup online du mercredi 3 mars? Si c'est OK pour toi, il me faudra juste un email pour que je t'envoie les infos pour les détails d'organisation.
