### ISSUE TITLE
React Hooks & React Context

### ISSUE THREAD

**Issue by AnaisMa** [parisjs/talks#82]
## React Hooks & React Context

*Talk format :* Long

*Description :*

> Ce talk présente le fonctionnement de React Hooks & React Context : quels sont leurs apports et comment en tirer parti dans la mise en place d'un state global, afin de se passer de solutions externes comme Redux.

*Slides :* 
*Projet :* 
*Twitter :*

**Comment by PierrickP** [comment]
Vous êtes l'auteure ?
