### ISSUE TITLE
Implémenter votre solution de paiement mobile sans angoisse

### ISSUE THREAD

**Issue by yassinecc** [parisjs/talks#83]
## Implémenter votre solution de paiement mobile sans angoisse

*Talk format :* Long

*Description :*

75% des utilisateurs en Europe règlent aujourd’hui régulièrement des achats sur mobile. Le public s’attend donc à une utilisation fiable et fluide du paiement au sein d’une application. Toutefois, les librairies JS à disposition des devs sont suffisamment flexibles pour occasionner des défauts d’implémentation qui peuvent être très vite inacceptables. 

J’aimerais partager avec vous les apprentissages et les défis relevés lors de l’un de mes précédents projets où notre équipe a mis en place des parcours de paiement recevant des transactions de l’ordre de la centaine d’euros, notamment comment : 

- 🔒 Avoir un système de paiement fiable et robuste
- 👨‍⚖️ Adhérer aux standards de sécurité nécessaires en cas d’audit 
- 😌 Assurer le maximum de transparence pour rassurer l’utilisateur dans une situation potentiellement anxiogène

*Slides :* WIP
*Twitter :* https://twitter.com/yassineccc

**Comment by Freddy03h** [comment]
Hello @yassinecc es tu disponible pour le meetup du 26 février ? Merci :)

**Comment by Freddy03h** [comment]
ping @yassinecc !

**Comment by yassinecc** [comment]
Bonjour @Freddy03h ça ne sera pas possible le 26 février :/ une autre date peut être ?

**Comment by Freddy03h** [comment]
Merci de la réponse ! Surement le mois prochain alors, dispo le 25 mars ?

**Comment by Freddy03h** [comment]
Hello @yassinecc dispo le 25 mars ?

**Comment by yassinecc** [comment]
Bonjour @Freddy03h , je ne suis peu disponible cette période et ne sais pas quand je reprendrai les meetups. Je préfère annuler mon intervention désolé :(
