### ISSUE TITLE
Server-side rendering, Twig, Vue, un ménage à 3 qui n'a pas fonctionné

### ISSUE THREAD

**Issue by cgaunet** [parisjs/talks#84]
## Server-side rendering, Twig, Vue, un ménage à 3 qui n'a pas fonctionné

*Talk format :* Long

*Description :*

Il y a 6 mois, j'ai rejoint le projet d'une plate-forme e-commerce: Tarkett, multinationale française spécialisée dans le revêtement de sols.

Initialement développé en Symfony, le site s'est progressivement orienté sur une solution hybride Symfony/Vue.js afin de rendre dynamiques certaines parties du site.

Je vous propose de voir ensemble comment la migration vers Nuxt.js nous a permis de diviser par 4 la métrique Visually Complete.

Je vous présenterai :
- Pourquoi l'architecture initiale Symfony/Vue n'était pas optimale. 
- Pourquoi et comment nous avons essayé de recoder Nuxt, sans succès... 
- Comment effectuer une migration progressive d'un site Twig/Vue vers une solution 100% Nuxt.
- Une comparaison des différentes solutions techniques sous l'angle du Speed Index.

En sortant, le public saura comment ajouter Vue/Nuxt sur un projet Symfony et repartira avec tous les tips pour réussir une migration progressive.

**Comment by Freddy03h** [comment]
Hello @cgaunet es tu disponible pour le meetup du 26 février ? Merci :)

**Comment by Freddy03h** [comment]
Ping @cgaunet !

**Comment by cgaunet** [comment]
Hello @Freddy03h je suis dispo ! Désolé pour le délai de réponse :)
