### ISSUE TITLE
The amazing tale of Internet S01E01: Pilot

### ISSUE THREAD

**Issue by loicortola** [parisjs/talks#9]
## The amazing tale of Internet S01E01: Pilot

*Talk format :* Long

*Description :*

> Amérique, début du 20e siècle.
> AT&T domine le marché de la téléphonie et se rapproche de Western Electric.
> Ensemble, ils fusionnent leurs départements de recherche et créent les Bell Labs.
> De l'autre côté de l'Atlantique, Sputnik, le premier satellite, est lancé en 1957, symbole de l'entrée dans l'ère spatiale.
> Un jeune ingénieur, Ken Thompson, rejoint les Bell Labs en 1966 et va changer le cours de l'histoire.
> #CERN #JS #AppletJava #Netscape #BrowserWars

*Slides :* undefined
*Projet :* undefined
*Twitter :* @loicortola

**Comment by PierrickP** [comment]
Marche de pair avec #10 (on peut le faire 2 mois d'affilés)
Vu en privé avec @loicortola il est theoriquement pris les derniers mercredi du mois.
On attend sa confirmation de dispo et on programme.
