### ISSUE TITLE
Gestion d'un monorepo JS avec Lerna et Verdaccio

### ISSUE THREAD

**Issue by ThamosIO** [parisjs/talks#90]
## Gestion d'un monorepo JS avec Lerna et Verdaccio

*Talk format :* Long

*Description :*

> Présentation des outils Lerna et Verdaccio dans un repository monolithique.

> Permet de gérer les releases de packages et librairies simplement et sans open sourcer ses packages.

> Les slides ne sont pas encore faites mais un article avec un sample project ont déjà été faits.

*Slides :* https://rednet.io/2019-05-29-lerna-verdaccio.html
*Projet :* https://github.com/rednetio/monorepo-lerna-example
*Twitter :* @rednetio

**Comment by mauricesvay** [comment]
Hello @ThamosIO !

Merci d'avoir proposé un sujet. On envisage de relancer les meetups dans une formule 100% en ligne, avec des talks un plus courts (10-15 minutes).

- Est-ce que ton sujet est toujours d'actualité?
- Est-ce qu'il pourrait être adapté à un format plus court?

**Comment by ThamosIO** [comment]
Hello @mauricesvay !

Oui et oui. Il faudra que je l'adapte un peu mais c'est faisable!

**Comment by mauricesvay** [comment]
@ThamosIO merci pour l'update ! On te recontactera si ton sujet est retenu pour un futur meetup !

**Comment by mauricesvay** [comment]
@ThamosIO ton talk a été retenu pour le meetup du mercredi 3 février 19h. Est-ce que tu pourrais confirmer si c'est OK pour toi?

**Comment by ThamosIO** [comment]
@mauricesvay Oui c'est OK pour moi 👍

**Comment by mauricesvay** [comment]
@ThamosIO super ! Est-ce qu'il y a un mail où je peux t'envoyer les détails sur le déroulement ?

**Comment by ThamosIO** [comment]
thomas.raimond@rednet.io
