### ISSUE TITLE
IoC, DI et cerise

### ISSUE THREAD

**Issue by izeau** [parisjs/talks#91]
## IoC, DI et cerise

*Talk format :* Long

*Description :*

> Salut !

> Alors l’idée ça serait de faire un talk en 3 étapes qui explique pourquoi l'IoC c'est pratique dès que sa codebase commence à s'étendre, à la fois pour le développement du produit lui-même mais surtout pour les tests. Live coding probablement… Un article est déjà fait, la présentation reprendra les grande lignes.

> En première partie, on montre pourquoi la façon de faire « classique » ne scale pas et met des bâtons dans les roues pour les tests unitaires. On modifie ensuite le code pour le rendre plus facilement testable.

> En seconde partie, on créée une solution de DI basée d'abord sur un container que l'on appelle comme une fonction, puis sur un Proxy ES6. On montre un cas concret (Injection de dépendance dans une API basée sur Express).

> En troisième partie, on introduit la bibliothèque _cerise_ (c'est du fait maison vous pouvez pas trouver plus authentique), qui reprend les concepts décrits en seconde partie et ajoute pas mal de helpers.

> Au plaisir de pouvoir monter sur l'estrade.

*Slides :* https://rednet.io/2019-07-03-ioc-di-et-cerise.html
*Projet :* https://www.npmjs.com/package/cerise
*Twitter :* @rednetio

**Comment by mauricesvay** [comment]
Hello @izeau !

Merci d'avoir proposé un sujet. On envisage de relancer les meetups dans une formule 100% en ligne, avec des talks un plus courts (10-15 minutes).

- Est-ce que ton sujet est toujours d'actualité?
- Est-ce qu'il pourrait être adapté à un format plus court?

**Comment by izeau** [comment]
Salut Maurice,

Tout à fait 👍

**Comment by mauricesvay** [comment]
@izeau merci pour l'update. Si ton talk est retenu pour un futur meetup, on te recontactera !

**Comment by Freddy03h** [comment]
Hello @izeau ! On tente de relancer les meetups, en physique cette fois (et format normal 20 min), est ce que tu serais dispo le mercredi 24 novembre pour nous proposer ton talk ? Merci 😀

**Comment by Freddy03h** [comment]
Talk plus proposé pour le moment, @izeau hésites pas à réouvrir quand tu le pourras
