### ISSUE TITLE
Tour d'horizon de Yarn 2!

### ISSUE THREAD

**Issue by arcanis** [parisjs/talks#94]
## Tour d'horizon de Yarn 2!

*Talk format :* Long

*Description :*

> Introduit il y a bientôt trois ans, Yarn s'est depuis lors taillé une solide place dans l'écosystème JavaScript grâce à sa mise au premier plan des problèmes de stabilité et de consistance. Il est maintenant temps de découvrir ce que Yarn 2 nous réserve, et vous dévoiler les prochaines étapes de notre plan visant à rendre vos applications plus stables, et vos cycles de développement plus abordables.

*Slides :* 
*Projet :* https://github.com/yarnpkg/berry
*Twitter :* @arcanis

**Comment by arcanis** [comment]
Notez que c'est un talk différent de https://github.com/parisjs/talks/issues/22. Même s'il s'agit en quelque sorte d'un followup, cette fois on va parler moins théorique et plus pratique, avec un aperçu des nouvelles fonctionnalités 💪

**Comment by Freddy03h** [comment]
Note : talk prévu pour le 27 novembre pour coïncider avec le meetup chez Datadog.

**Comment by Freddy03h** [comment]
Erratum : le meetup chez Datadog c'est le 30 octobre en fait 😅, ok pour toi @arcanis ? Merci.

**Comment by arcanis** [comment]
Ahah j'avais pas capté - oui pas de soucis, c'est ce que j'avais noté 😄
