### ISSUE TITLE
Introduction à RabbitMQ

### ISSUE THREAD

**Issue by KajanSiva** [parisjs/talks#95]
## Introduction à RabbitMQ

*Talk format :* Long

*Description :*

> Les architectures microservices ont le vent en poupe. Mais savez-vous que la colonne vertébrale de cette architecture contient toujours un "message broker" ?
> Je vous propose d'en découvrir un des plus célèbres : RabbitMQ. On passera en revue les notions fondamentales de cet outil. Avec ses avantages, ses inconvénients et quelques cas d'usages.

*Slides :* 
*Projet :* 
*Twitter :* @KajanSiva

**Comment by KajanSiva** [comment]
Hello @PierrickP,
C'est la première fois que je soumet un sujet de talk pour Paris.js. Quels sont vos process pour avancer dans les colonnes de planification sur Trello ?

**Comment by PierrickP** [comment]
Hello @KajanSiva,
merci pour ta proposition. En général c'est nous qui avançons les cartes.
On fait une réunion en début de mois pour planifier le meetup suivant ou celui d'après.
On essaye parfois de regrouper les talks par theme sinon on pioche dans les anciens

**Comment by mauricesvay** [comment]
Hello @KajanSiva !

Merci d'avoir proposé un sujet. On envisage de relancer les meetups dans une formule 100% en ligne, avec des talks un plus courts (10-15 minutes).

- Est-ce que ton sujet est toujours d'actualité?
- Est-ce qu'il pourrait être adapté à un format plus court?

**Comment by Freddy03h** [comment]
Hello @KajanSiva ! On tente de relancer les meetups, en physique cette fois (et format normal 20 min), est ce que tu serais dispo le mercredi 24 novembre pour nous proposer ton talk ? Merci 😀
