### ISSUE TITLE
Comiler-Driven-Onboarding : open source in elm

### ISSUE THREAD

**Issue by sebsheep** [parisjs/talks#97]
## Comiler-Driven-Onboarding : open source in elm

*Talk format :* Long

*Description :*

De la première "good first issue" résolue jusqu'à une PR conséquente, je raconterai comment j'ai intégré le projet open source elm-in-elm (https://github.com/elm-in-elm/compiler).

En suivant pas à pas mon expérience, nous verrons comment :
* simplifier des tests ;
* ajouter de nouvelles de fonctionnalités sans se perdre dans le code ;
* éviter un bug sournois avant même de compiler ;
* détecter un bug alors que "tout semble marcher" ;
* modifier le code pour que les nouveaux contributeurs ne tombent pas dans le même piège que moi ;
* aider les nouveaux contributeurs à participer au projet.

Ce projet a de plus la particularité d'être un compilateur. Ces différents points s'intercaleront donc avec des explications sur le processus de compilation... L'occasion de réaliser que ces logiciels sont certes complexes, mais tout à fait abordables !

*Slides :* https://slides.com/sebbes/compiler-driven-onboarding
*Projet :* https://github.com/elm-in-elm/compiler
*Twitter :*

**Comment by mauricesvay** [comment]
Hello @sebsheep !

Merci d'avoir proposé un sujet. On envisage de relancer les meetups dans une formule 100% en ligne, avec des talks un plus courts (10-15 minutes).

- Est-ce que ton sujet est toujours d'actualité?
- Est-ce qu'il pourrait être adapté à un format plus court?

**Comment by sebsheep** [comment]
Salut @mauricesvay ,

Niveau longueur, non 20 minutes aurait été déjà un peu court. Au niveau du contenu, je m'interroge sur la pertinence de proposer ce talk ici vu qu'il ne s'agit pas du tout de JS en fait.

**Comment by mauricesvay** [comment]
@sebsheep n'hésite pas à fermer l'issue GitHub dans ce cas :)
